// The long tail of lead-handling scenarios, grouped under headers.
//
// Each entry is still a full instruction: why it exists, how to execute, what
// not to do, what can go wrong, and the if/else branches. They are written
// tighter than the six core labels because they are read on the floor mid-shift.

import type { LeadLabelDef } from "./catalog";

type Draft = Omit<LeadLabelDef, "branches"> & { branches: [string, string][] };

function L(d: Draft): LeadLabelDef {
  return { ...d, branches: d.branches.map(([condition, then]) => ({ condition, then })) };
}

export const SUB_LABELS: LeadLabelDef[] = [
  // ─────────────────────────── SPEED & RESPONSE ───────────────────────────
  L({
    id: "first-reply-late", group: "speed", label: "First reply took too long", short: "Slow first reply",
    severity: "critical", slaHours: 1,
    why: "The first reply window decides most of our conversion. A lead answered inside five minutes converts several times better than the same lead answered in an hour, because the customer is enquiring on three platforms at once and rewards whoever shows up first.",
    howToExecute: [
      "Open the thread and note the gap between their first message and our first reply — put the actual minutes in the note.",
      "Reply now with an apology-free opener that adds value: one relevant option plus one question.",
      "Check whether the delay was personal (agent busy) or systemic (nobody was on the queue at that hour) and say which in the note.",
    ],
    whatNotToDo: [
      "Do not open with 'sorry for the delay' — it draws attention to the gap and invites them to compare us with the fast competitor.",
      "Do not blame the queue in the customer chat.",
    ],
    problemsThatCanOccur: [
      "The customer has already paid a token elsewhere; you will hear silence, not rejection.",
      "The same hour keeps repeating in the data because it is a rota hole, not an agent problem.",
    ],
    branches: [
      ["Gap is under 30 minutes and the customer is still replying", "Coach quietly, no escalation, keep working the lead."],
      ["Gap is over 2 hours", "Escalate to the shift lead and check who was on the queue at that hour."],
      ["Gap repeats at the same time every day", "This is a staffing problem, not a label — raise it in the daily huddle."],
    ],
    doneWhen: "A fresh reply exists and the cause of the delay is written on the lead.",
    quickNotes: ["First reply after 2h+ — customer had already asked twice", "Enquiry landed at night, nobody on queue"],
  }),
  L({
    id: "dead-air", group: "speed", label: "Dead air — nobody has spoken in 24h", short: "Dead air 24h",
    severity: "action", slaHours: 4,
    why: "A thread with no message from either side for a day is not warm, it is cooling. The cost of one message today is nothing; the cost of restarting a dead thread next week is a whole conversation.",
    howToExecute: [
      "Read the last three messages and find the unfinished thread — a question they asked, an option we promised, a slot we never confirmed.",
      "Restart with that specific unfinished item, never with a greeting.",
      "Set a dated next action before closing the lead.",
    ],
    whatNotToDo: [
      "Do not send 'Hi, any update?' — it is the single most ignored message we send.",
      "Do not restart with a fresh pitch that ignores everything already discussed.",
    ],
    problemsThatCanOccur: [
      "The silence is ours because we owe them information we never got from the owner.",
      "Multiple dead threads get bulk-messaged with the same line and the customer sees the template.",
    ],
    branches: [
      ["We owe them something", "Deliver it, then ask for the decision."],
      ["They owe us an answer", "Send a two-option question so replying costs them one word."],
      ["Dead more than 7 days", "Treat it as revival, not follow-up — change channel and angle."],
    ],
    doneWhen: "A new message with substance is in the thread and a next action is dated.",
    quickNotes: ["No message either side since yesterday", "We promised options and never sent them"],
  }),
  L({
    id: "unanswered-last-message", group: "speed", label: "Customer's last message is still unanswered", short: "They spoke last",
    severity: "critical", slaHours: 1,
    why: "Nothing damages trust faster than a customer who can see their own message sitting unanswered. Every hour it sits, the reply we eventually send has to work harder.",
    howToExecute: [
      "Answer the actual question first, in the first line, before any pitch.",
      "If you cannot answer yet, say when you will — with a specific time, not 'soon'.",
      "Then add one forward step: a slot, an option, a confirmation.",
    ],
    whatNotToDo: [
      "Do not reply with a different topic and hope they forget the question.",
      "Do not mark this done by sending a holding message with no time commitment.",
    ],
    problemsThatCanOccur: [
      "The answer needs the owner and the owner is unreachable — that becomes an owner-side label too.",
      "Someone answers on call and never writes it in the thread, so the review still shows silence.",
    ],
    branches: [
      ["The question is answerable now", "Answer in one line, then move forward."],
      ["The answer needs the owner", "Send the holding message with a time, and raise the owner label in parallel."],
    ],
    doneWhen: "The customer's question is answered in writing in the same thread.",
    quickNotes: ["Customer asked about rent 3 days ago, no reply", "They sent documents, nobody acknowledged"],
  }),
  L({
    id: "night-gap", group: "speed", label: "Enquiry came outside hours and was never picked up", short: "Night gap",
    severity: "action", slaHours: 2,
    why: "Most rental enquiries arrive after work. If the night and early-morning windows are unmanned, we are handing the highest-intent hours to competitors.",
    howToExecute: [
      "Reply at the earliest working minute with a message that references their timestamp: 'Saw your message last night about Koramangala…'.",
      "Offer the earliest realistic slot the same day.",
      "Log the hour so the rota can be corrected.",
    ],
    whatNotToDo: ["Do not pretend the reply is instant when the timestamp is visible.", "Do not batch all night enquiries with one identical text."],
    problemsThatCanOccur: ["High-intent leads at 11pm are also enquiring elsewhere at 11pm.", "The rota never changes because nobody records the hour."],
    branches: [
      ["Enquiry after 10pm", "Reply first thing, apologise with an offer, not words."],
      ["It happens daily in the same window", "Escalate as a staffing gap."],
    ],
    doneWhen: "Reply sent within the first working hour and the hour is logged.",
    quickNotes: ["Came in at 11:40pm, first reply next afternoon"],
  }),
  L({
    id: "response-drop", group: "speed", label: "Replies started fast, then slowed down", short: "Pace dropped",
    severity: "coaching", slaHours: 6,
    why: "Customers read our response speed as how much we want them. A thread that starts in seconds and drifts to hours tells them they are now a low priority — usually right before they stop replying.",
    howToExecute: [
      "Compare the reply gaps across the thread and name the point where it slowed.",
      "Re-establish pace with two fast, useful replies in a row.",
      "Find out what pulled the owner away — capacity, tours, or a lost thread.",
    ],
    whatNotToDo: ["Do not compensate with a long message; compensate with speed.", "Do not slow down again after one fast reply."],
    problemsThatCanOccur: ["The agent is genuinely at capacity and the lead should be reassigned.", "Speed comes back but quality drops."],
    branches: [
      ["The owner is at capacity", "Reassign rather than coach."],
      ["The owner has room", "Coach on prioritisation and re-check tomorrow."],
    ],
    doneWhen: "Two consecutive quick, substantive replies exist after the label.",
    quickNotes: ["Replies within 1 min on day 1, 6h by day 3"],
  }),

  // ─────────────────────── QUALIFICATION & QUESTIONS ───────────────────────
  L({
    id: "budget-unknown", group: "questions", label: "Budget is still unknown", short: "No budget",
    severity: "action", slaHours: 4,
    why: "Without a budget we send the wrong options, waste tours and negotiate blind. Budget is the single field that changes every subsequent action.",
    howToExecute: [
      "Ask as a two-option range, not an open question: 'closer to 12k or 18k?'.",
      "Attach a reason so it does not feel like screening: 'so I only send you what fits'.",
      "Write the answer, and the flexibility around it, on the lead record.",
    ],
    whatNotToDo: ["Do not ask 'what is your budget' cold as the opening line.", "Do not assume the budget from the area they named."],
    problemsThatCanOccur: ["They quote a low anchor to test us and later move up.", "The budget is per-head in a sharing case and gets recorded as total."],
    branches: [
      ["It is a group booking", "Capture per-head and total separately."],
      ["They refuse to state a number", "Send two options at different price points and read which one they engage with."],
    ],
    doneWhen: "A budget range exists on the lead record, with a note on flexibility.",
    quickNotes: ["Budget never asked in 40 messages", "Only area discussed, no price"],
  }),
  L({
    id: "movein-unknown", group: "questions", label: "Move-in date is still unknown", short: "No move-in date",
    severity: "action", slaHours: 4,
    why: "The move-in date sets the urgency, the follow-up cadence and whether this lead belongs in today's queue at all. Without it we treat a next-month lead like a today lead and vice versa.",
    howToExecute: [
      "Ask in buckets — this week, this month, or later. Buckets get answered; exact dates get avoided.",
      "Record the bucket and the reason behind it (notice period, lease end, joining date).",
      "Set the cadence from the bucket, not from habit.",
    ],
    whatNotToDo: ["Do not accept 'soon' as an answer.", "Do not chase a 60-day lead daily."],
    problemsThatCanOccur: ["The date is driven by someone else — a job offer or a parent.", "The date slips and nobody updates the record."],
    branches: [
      ["Within 7 days", "Tour today or tomorrow, no exceptions."],
      ["Beyond 30 days", "Move to nurture cadence and set a dated wake-up."],
    ],
    doneWhen: "A move-in bucket is on the record and the follow-up cadence matches it.",
    quickNotes: ["No date asked at all", "Said 'soon', never pinned down"],
  }),
  L({
    id: "decision-maker-unknown", group: "questions", label: "We are talking to someone who cannot decide", short: "Not the decider",
    severity: "action", slaHours: 6,
    why: "Deals stall at the last step when the person paying or approving never entered the conversation. Finding them early is cheaper than convincing them late.",
    howToExecute: [
      "Ask who else needs to see the place before they book, and offer to include them.",
      "Get that person's name and, ideally, their number or a group chat.",
      "Send the decision-maker a short summary they can read without scrolling the whole thread.",
    ],
    whatNotToDo: ["Do not go around the person you are speaking to — bring them along.", "Do not repeat the entire pitch to the second person; summarise."],
    problemsThatCanOccur: ["The decider has a different budget in mind.", "Adding a parent slows a decision that was almost made."],
    branches: [
      ["Parent or spouse approves", "Offer a video walkthrough for them specifically."],
      ["Company or HR pays", "Ask for the invoicing and approval process before quoting."],
    ],
    doneWhen: "The decision-maker is identified on the record and has received something directly.",
    quickNotes: ["Roommate decides, never contacted", "Parents pay — never looped in"],
  }),
  L({
    id: "area-vague", group: "questions", label: "Location need is vague or unworkable", short: "Vague area",
    severity: "action", slaHours: 6,
    why: "'Anywhere in Bangalore' is not a requirement. Without a commute anchor we send options they will never visit, and the tour no-show rate goes up.",
    howToExecute: [
      "Ask for the anchor, not the area: office, college or metro station they travel to daily.",
      "Confirm the maximum acceptable commute in minutes.",
      "Convert that into two or three concrete micro-markets and confirm them back.",
    ],
    whatNotToDo: ["Do not send a list from five different parts of the city.", "Do not assume the area from their current address."],
    problemsThatCanOccur: ["Their office is changing soon and the anchor moves.", "They name a premium area their budget cannot serve."],
    branches: [
      ["Budget and area do not match", "Show the honest trade-off — same budget nearby, or same area smaller room."],
      ["No fixed anchor yet", "Park them in nurture until the anchor exists."],
    ],
    doneWhen: "Two or three named micro-markets are confirmed on the record.",
    quickNotes: ["Says 'anywhere', no commute anchor asked"],
  }),
  L({
    id: "occupancy-unknown", group: "questions", label: "Occupancy / sharing preference not captured", short: "No occupancy",
    severity: "coaching", slaHours: 8,
    why: "Single, double and triple change the price by thousands. Sending the wrong occupancy makes our pricing look random and forces a second round of options.",
    howToExecute: ["Ask single or sharing, and if sharing, with whom.", "Confirm gender preference and food preference in the same breath if relevant.", "Record all three."],
    whatNotToDo: ["Do not default to single because it is easier to quote.", "Do not ask four preference questions in one block."],
    problemsThatCanOccur: ["They will share only with a known friend, which changes availability.", "Preference changes once they see the price difference."],
    branches: [
      ["Sharing with a named friend", "Treat as a group lead and capture the second person."],
      ["Open to either", "Quote both and let the price decide."],
    ],
    doneWhen: "Occupancy preference is on the record.",
    quickNotes: ["Quoted single price, never asked about sharing"],
  }),
  L({
    id: "group-not-mapped", group: "questions", label: "It is a group booking and the group is not mapped", short: "Group not mapped",
    severity: "action", slaHours: 8,
    why: "Group deals are won or lost on the member nobody spoke to. If we only know one of four people, we are negotiating with a quarter of the decision.",
    howToExecute: ["Get the headcount and the names.", "Identify who pays and who decides — they are often different people.", "Capture each person's move-in date; staggered dates change the whole plan."],
    whatNotToDo: ["Do not assume the loudest person decides.", "Do not quote a group price before you know the headcount."],
    problemsThatCanOccur: ["One member drops and the whole deal resets.", "Different budgets inside the same group."],
    branches: [
      ["Staggered move-in dates", "Ask whether rooms can be held, and price the holding honestly."],
      ["One member is unreachable", "Ask the group to add them to a WhatsApp group with us."],
    ],
    doneWhen: "Headcount, names and the payer are on the record.",
    quickNotes: ["3 friends moving, only 1 contacted"],
  }),
  L({
    id: "requirements-drifted", group: "questions", label: "Their requirement changed and we are still on the old one", short: "Requirement changed",
    severity: "action", slaHours: 4,
    why: "Customers change budgets, areas and dates mid-conversation. Continuing on the old brief makes every option feel wrong and makes us look like we are not listening.",
    howToExecute: ["Quote the message where the requirement changed.", "Confirm the new brief back in one line and get a yes.", "Update the record and re-run the matching."],
    whatNotToDo: ["Do not keep pushing the shortlist you already prepared.", "Do not silently update the record without confirming with them."],
    problemsThatCanOccur: ["They flip back again next week.", "The old shortlist was already promised to the owner."],
    branches: [
      ["Budget went down", "Re-match honestly, do not stretch them."],
      ["Area changed", "Check whether the zone owner should change too."],
    ],
    doneWhen: "The new brief is confirmed by the customer in writing and the record matches.",
    quickNotes: ["Changed area on day 2, still sent old zone options"],
  }),

  // ───────────────────────── FOLLOW-UP DISCIPLINE ─────────────────────────
  L({
    id: "no-next-action", group: "followup", label: "No next action is set on this lead", short: "No next action",
    severity: "critical", slaHours: 2,
    why: "A lead without a dated next action is a lead nobody will touch again. This is the most common way live leads quietly die in any CRM.",
    howToExecute: ["Decide the single next step and date it.", "Write what will be said or sent, not just 'call'.", "If there is genuinely no next step, close the lead with a reason instead of leaving it open."],
    whatNotToDo: ["Do not set a vague 'follow up later'.", "Do not set five actions to look busy."],
    problemsThatCanOccur: ["Actions get set and never done, which is worse than none.", "The date is set far out to keep the dashboard clean."],
    branches: [
      ["The lead is still active", "Set the next action within 48 hours."],
      ["The lead is genuinely dead", "Close it with a reason so the pipeline stays honest."],
    ],
    doneWhen: "A dated, specific next action exists on the lead.",
    quickNotes: ["Active lead, empty next action for 5 days"],
  }),
  L({
    id: "generic-followup", group: "followup", label: "Follow-up was generic — 'any update?'", short: "Generic nudge",
    severity: "coaching", slaHours: 12,
    why: "A follow-up with no new information hands the work back to the customer. It teaches them that our messages can be ignored safely.",
    howToExecute: ["Find one piece of new information: a new unit, a price hold, a slot, an owner answer.", "Lead with it, then make one clear ask.", "Keep it under four lines."],
    whatNotToDo: ["Do not send 'Hello?', 'Any update?', or a lone question mark.", "Do not resend the same options with new words."],
    problemsThatCanOccur: ["There genuinely is nothing new — then create something: a hold, a slot, a comparison.", "The customer blocks us after repeated nudges."],
    branches: [
      ["We have nothing new", "Create value: hold a room, arrange an evening slot, or send a comparison."],
      ["Third generic nudge already sent", "Stop, switch channel, and change the angle completely."],
    ],
    doneWhen: "A follow-up carrying new information and one ask is in the thread.",
    quickNotes: ["Three 'any update?' messages in a row"],
  }),
  L({
    id: "promise-broken", group: "followup", label: "We promised something and did not deliver", short: "Broken promise",
    severity: "critical", slaHours: 2,
    why: "A missed promise is the fastest way to lose a customer who was ready to pay. They stop believing the next thing we say, including the price.",
    howToExecute: ["Find the promise in the thread and quote it in the note.", "Deliver it now, or give a specific new time with a reason.", "Acknowledge the miss in one short line — no paragraph of apology."],
    whatNotToDo: ["Do not pretend the promise was never made.", "Do not promise again without checking you can deliver."],
    problemsThatCanOccur: ["The promise depended on an owner who never replied.", "Multiple promises are outstanding and only one gets fixed."],
    branches: [
      ["Deliverable now", "Deliver and continue."],
      ["Blocked by the owner", "Tell the customer the truth with a time, and raise the owner label."],
    ],
    doneWhen: "The promised item is delivered or re-committed with a specific time.",
    quickNotes: ["Promised photos yesterday, never sent", "Said 'will call at 6', never called"],
  }),
  L({
    id: "commitment-not-tracked", group: "followup", label: "Customer made a commitment and nobody tracked it", short: "Untracked promise",
    severity: "action", slaHours: 6,
    why: "'I'll decide by Sunday' is a free deadline the customer gave us. Not tracking it wastes the strongest, least pushy follow-up hook we ever get.",
    howToExecute: ["Record the exact words and the date.", "Set the follow-up for that date, not before.", "Open the follow-up by quoting their own commitment."],
    whatNotToDo: ["Do not chase before the date they named — it breaks the trust of asking.", "Do not let the date pass silently."],
    problemsThatCanOccur: ["They miss their own deadline and go quiet out of guilt — make it easy to return.", "The commitment was a soft brush-off."],
    branches: [
      ["Date arrives and they are silent", "One warm message quoting the commitment, then a decision either way."],
      ["They renegotiate", "Accept once, record the new date, and treat a second slip as a soft no."],
    ],
    doneWhen: "The commitment and its date are on the record with a matching follow-up.",
    quickNotes: ["Said 'will confirm Sunday' — no reminder set"],
  }),
  L({
    id: "over-following", group: "followup", label: "We are following up too aggressively", short: "Over-following",
    severity: "coaching", slaHours: 12,
    why: "Daily messages on a silent thread get us blocked and marked as spam, which costs us the number, not just the lead.",
    howToExecute: ["Count the consecutive unanswered messages and put the number in the note.", "Stop for a cycle, then return with one high-value message.", "Move the lead to the correct cadence for its move-in date."],
    whatNotToDo: ["Do not send from a second number after being ignored on the first.", "Do not message multiple members of the same group simultaneously."],
    problemsThatCanOccur: ["The customer reports the number.", "Aggression is hiding a targets problem, not a lead problem."],
    branches: [
      ["Four or more unanswered", "One close-the-loop message, then nurture."],
      ["They asked us to stop", "Stop immediately and record the preference."],
    ],
    doneWhen: "Cadence is corrected and the thread has room to breathe.",
    quickNotes: ["6 unanswered messages in 2 days"],
  }),
  L({
    id: "wrong-channel", group: "followup", label: "We keep using a channel they never answer on", short: "Wrong channel",
    severity: "coaching", slaHours: 12,
    why: "Some customers only pick up calls, others only reply on WhatsApp. Repeating a channel they ignore is effort that reads as zero effort in the data.",
    howToExecute: ["Look at where they ever responded and switch to that channel.", "If they have never responded anywhere, change the hour before changing the words.", "Record the channel preference on the lead."],
    whatNotToDo: ["Do not call five times in a row when they reply happily on chat.", "Do not switch channels mid-negotiation without telling them."],
    problemsThatCanOccur: ["Number is WhatsApp-only or call-only.", "Their work hours block calls entirely."],
    branches: [
      ["Never answers calls but replies on chat", "Go chat-first and use calls only for closing."],
      ["Replies only in the evening", "Move all touches into that window."],
    ],
    doneWhen: "Channel preference is recorded and the next touch uses it.",
    quickNotes: ["7 missed calls, replies instantly on WhatsApp"],
  }),

  // ─────────────────────── OWNER & INVENTORY SIDE ───────────────────────
  L({
    id: "owner-silent", group: "owner", label: "Owner is not responding to us", short: "Owner silent",
    severity: "critical", slaHours: 4,
    why: "An unresponsive owner stalls a live customer. The customer does not care whose fault it is — they only see us going quiet.",
    howToExecute: [
      "Try the owner on call, then WhatsApp, with a single clear ask and a deadline.",
      "Tell the customer honestly that we are confirming with the property and give a time.",
      "If the owner misses the deadline, offer the customer an alternative property in the same budget.",
    ],
    whatNotToDo: ["Do not leave the customer waiting silently while chasing the owner.", "Do not promise availability you have not confirmed."],
    problemsThatCanOccur: ["The unit is already gone and the owner is avoiding the call.", "The owner responds only to one person on our team."],
    branches: [
      ["Owner silent over 24h", "Switch the customer to alternatives and flag the property as unreliable."],
      ["Owner responds to a colleague", "Route through them instead of escalating."],
    ],
    doneWhen: "Either the owner has answered, or the customer has been moved to a live alternative.",
    quickNotes: ["Owner not picking up for 2 days, customer waiting"],
  }),
  L({
    id: "owner-no-followup-view", group: "owner", label: "Owner is not actively seeing our follow-ups", short: "Owner inactive",
    severity: "action", slaHours: 12,
    why: "If the owner is not reading updates, tours get declined at the door, prices go stale, and our team burns time on inventory that is not really available.",
    howToExecute: ["Check when the owner last opened or responded to anything.", "Call once to re-establish contact and confirm live availability room by room.", "Mark the property's reliability so matching can down-rank it."],
    whatNotToDo: ["Do not keep sending updates into a channel nobody reads.", "Do not show unverified inventory to a high-intent customer."],
    problemsThatCanOccur: ["Owner has appointed a caretaker who is the real contact.", "Property is listed with several agencies and is often already booked."],
    branches: [
      ["No contact in 7 days", "Down-rank the property until re-verified."],
      ["Caretaker is the real contact", "Update the owner record with the right person."],
    ],
    doneWhen: "Availability is re-verified with a human and the record reflects it.",
    quickNotes: ["Owner has not opened updates in a week"],
  }),
  L({
    id: "inventory-stale", group: "owner", label: "Availability is stale or unverified", short: "Stale availability",
    severity: "critical", slaHours: 2,
    why: "Showing a room that is already taken destroys trust in one message and often ends the conversation entirely.",
    howToExecute: ["Verify with the owner before sending anything else.", "Update the record immediately, including the date of verification.", "If it is gone, send two alternatives in the same message as the correction."],
    whatNotToDo: ["Do not send a shortlist you have not verified this week.", "Do not correct without an alternative."],
    problemsThatCanOccur: ["The customer already planned their day around a visit.", "The same stale unit keeps resurfacing in matching."],
    branches: [
      ["Customer already booked a tour", "Call, do not text, and offer a replacement visit in the same trip."],
      ["Unit is gone permanently", "Remove it from active inventory today."],
    ],
    doneWhen: "Availability is verified and dated on the property record.",
    quickNotes: ["Sent a unit that was booked last week"],
  }),
  L({
    id: "media-missing", group: "owner", label: "Photos or videos are missing or misleading", short: "Media gap",
    severity: "action", slaHours: 12,
    why: "Customers shortlist on media. Missing photos mean no shortlist; misleading photos mean a wasted tour and a bad review.",
    howToExecute: ["List exactly what is missing: room, bathroom, kitchen, common area, building entrance.", "Request it from the owner with a deadline, or schedule our own capture.", "Never send a shortlist that relies on imagination."],
    whatNotToDo: ["Do not reuse photos of a different room in the same building.", "Do not send heavily edited images."],
    problemsThatCanOccur: ["Owner sends low-quality phone photos that hurt more than help.", "Media exists but is not linked to the right room."],
    branches: [
      ["Customer is remote", "Media is blocking — arrange a live video walkthrough today."],
      ["Customer is local", "Push straight to a physical visit instead of waiting for photos."],
    ],
    doneWhen: "The named media exists on the property record or a walkthrough is booked.",
    quickNotes: ["No bathroom or kitchen photos for the unit we are pushing"],
  }),
  L({
    id: "price-unconfirmed", group: "owner", label: "Price or deposit is not confirmed with the owner", short: "Price unconfirmed",
    severity: "critical", slaHours: 2,
    why: "Quoting an unconfirmed price creates a renegotiation at the worst possible moment — after the customer has emotionally committed.",
    howToExecute: ["Confirm rent, deposit, notice period, maintenance and what is included, in writing from the owner.", "Quote only after that.", "Store the confirmation date on the property record."],
    whatNotToDo: ["Do not quote from an old listing.", "Do not leave the deposit vague and 'discuss later'."],
    problemsThatCanOccur: ["Owner changes the price when demand rises.", "Hidden charges appear at agreement stage."],
    branches: [
      ["Already quoted an unconfirmed number", "Correct it immediately and escalate — see the wrong-info label."],
      ["Owner refuses to commit in writing", "Flag the property as high-risk for closing."],
    ],
    doneWhen: "Written price confirmation exists and matches what the customer was told.",
    quickNotes: ["Quoted 14k, owner never confirmed"],
  }),
  L({
    id: "owner-rules-unclear", group: "owner", label: "House rules and restrictions were never shared", short: "Rules unclear",
    severity: "action", slaHours: 8,
    why: "Food restrictions, curfews, guest policies, gender rules and pet rules cause most late-stage cancellations. Surfacing them early costs one message; surfacing them late costs the booking.",
    howToExecute: ["List the rules that actually apply to this customer's life.", "Share them plainly before the tour, not after.", "Record their reaction — objections here predict cancellations."],
    whatNotToDo: ["Do not hide a restriction to protect the tour.", "Do not read out a generic rulebook."],
    problemsThatCanOccur: ["Customer discovers a rule at the door and walks out.", "Rules differ per floor or per owner and nobody knows the truth."],
    branches: [
      ["Rule is a hard blocker for them", "Re-match instead of persuading."],
      ["Rule is negotiable", "Get the owner's exception in writing before promising it."],
    ],
    doneWhen: "Applicable rules are shared in writing and the reaction is recorded.",
    quickNotes: ["Non-veg customer, veg-only building, never mentioned"],
  }),

  // ─────────────────────────── TOURS & VISITS ───────────────────────────
  L({
    id: "tour-not-offered", group: "tour", label: "Interested customer was never offered a tour", short: "No tour offered",
    severity: "critical", slaHours: 4,
    why: "Nobody rents a room from a photo. The tour is the conversion event; every message that does not move toward it is overhead.",
    howToExecute: ["Offer two specific slots, not 'when are you free?'.", "Offer to pick the nearest property first so the trip feels small.", "Confirm the slot with an address, a pin and a contact name."],
    whatNotToDo: ["Do not wait for the perfect shortlist before offering a visit.", "Do not offer an open-ended 'anytime'."],
    problemsThatCanOccur: ["The customer is in another city — offer a video tour instead.", "Slots are offered without checking the owner's availability."],
    branches: [
      ["Customer is local", "Offer today and tomorrow, two slots each."],
      ["Customer is remote", "Book a live video walkthrough and treat it as the tour."],
    ],
    doneWhen: "A dated tour or video walkthrough is booked and confirmed.",
    quickNotes: ["Hot lead, 30 messages, no tour offered"],
  }),
  L({
    id: "tour-unconfirmed", group: "tour", label: "Tour is booked but never reconfirmed", short: "Tour unconfirmed",
    severity: "action", slaHours: 4,
    why: "Unconfirmed tours are the biggest source of no-shows. A single reconfirmation the evening before lifts attendance dramatically.",
    howToExecute: ["Reconfirm the evening before with time, address, pin and the name of who will meet them.", "Ask for a yes, not silence.", "Reconfirm again two hours before for morning slots."],
    whatNotToDo: ["Do not treat silence as confirmation.", "Do not send only a location pin without a time and a name."],
    problemsThatCanOccur: ["The owner or caretaker is not informed and nobody opens the door.", "Traffic or weather kills the slot — offer a fallback."],
    branches: [
      ["No response to reconfirmation", "Call. If still silent, release the slot and offer another."],
      ["They confirm", "Inform the property contact and log it."],
    ],
    doneWhen: "An explicit customer confirmation and an informed property contact both exist.",
    quickNotes: ["Tour tomorrow 11am, no reconfirmation sent"],
  }),
  L({
    id: "tour-noshow-unworked", group: "tour", label: "Tour no-show was never followed up", short: "No-show ignored",
    severity: "action", slaHours: 4,
    why: "A no-show is not a rejection. Most no-shows are logistics, and a same-day rebook recovers a large share of them — but only on the same day.",
    howToExecute: ["Call within the hour, with curiosity rather than accusation.", "Offer an immediate alternative slot.", "Record the real reason so the pattern can be fixed."],
    whatNotToDo: ["Do not send a passive-aggressive message about wasted time.", "Do not wait a day to react."],
    problemsThatCanOccur: ["They already visited a competitor's place instead.", "The no-show was ours — nobody opened the door."],
    branches: [
      ["It was our fault", "Apologise concretely and offer a priority slot with a senior person."],
      ["They went cold", "One rebook offer, then move to nurture."],
    ],
    doneWhen: "A reason is recorded and either a rebooked slot or a nurture move exists.",
    quickNotes: ["Missed 3pm visit, no call afterwards"],
  }),
  L({
    id: "tour-outcome-missing", group: "tour", label: "Tour happened but no outcome was recorded", short: "No tour outcome",
    severity: "critical", slaHours: 4,
    why: "A tour with no recorded outcome is a wasted asset — we spent the most expensive resource we have and kept none of the learning.",
    howToExecute: ["Record what they liked, what they rejected, and the one thing stopping the booking.", "Record the price reaction specifically.", "Set the closing next action the same day."],
    whatNotToDo: ["Do not record 'good visit' as an outcome.", "Do not wait until the next morning to write it."],
    problemsThatCanOccur: ["Feedback lives only in the agent's head and is lost on reassignment.", "Owner asks for feedback and we have none."],
    branches: [
      ["Positive but unbooked", "Same-day closing attempt with a hold or a light incentive."],
      ["Negative", "Capture the exact objection and re-match immediately."],
    ],
    doneWhen: "A structured outcome with the blocking objection is on the lead.",
    quickNotes: ["Visited yesterday, nothing written"],
  }),
  L({
    id: "post-tour-silence", group: "tour", label: "Went quiet after a positive tour", short: "Post-tour silence",
    severity: "critical", slaHours: 4,
    why: "This is the highest-value silence in the funnel. A customer who visited and liked it is comparing us with one other option right now, and the response speed decides it.",
    howToExecute: ["Call the same day; do not text-only.", "Give one concrete reason to decide today: a hold, a slot, a room going.", "Ask the closing question directly."],
    whatNotToDo: ["Do not wait three days to 'give them space'.", "Do not discount before you know the objection."],
    problemsThatCanOccur: ["They are waiting on a parent or a salary date.", "A competitor gave them a deadline first."],
    branches: [
      ["Waiting on someone else", "Get that person on a call or a video walkthrough."],
      ["Waiting on money", "Ask for the date and offer a hold, not a discount."],
    ],
    doneWhen: "A call happened and the true blocker is recorded.",
    quickNotes: ["Loved the place on Monday, silent since"],
  }),

  // ──────────────────── PRICING, PAYMENT & CLOSING ────────────────────
  L({
    id: "no-close-attempt", group: "money", label: "Nobody ever asked for the booking", short: "Never asked",
    severity: "critical", slaHours: 4,
    why: "Long friendly threads that never ask for the decision are the most common shape of a lost lead. Information does not close; asking does.",
    howToExecute: ["Ask directly: 'Shall I hold this room for you today?'.", "Give a reason for today — a hold, a slot, availability.", "If the answer is no, get the reason, not a polite exit."],
    whatNotToDo: ["Do not bury the ask at the end of a long paragraph.", "Do not ask twice in the same message."],
    problemsThatCanOccur: ["Asking too early on an unqualified lead breaks rapport.", "The ask is made and the objection is not handled."],
    branches: [
      ["They visited and liked it", "Ask today."],
      ["They have not visited", "Ask for the visit, not the booking."],
    ],
    doneWhen: "An explicit ask exists in the thread and the answer or objection is recorded.",
    quickNotes: ["50 messages, never asked for the booking"],
  }),
  L({
    id: "objection-unhandled", group: "money", label: "An objection was raised and never handled", short: "Objection dropped",
    severity: "critical", slaHours: 2,
    why: "An unanswered objection does not disappear — it becomes the reason they stop replying. Every dropped objection is a lost deal we never learn from.",
    howToExecute: ["Quote the objection in the note, in the customer's own words.", "Answer it directly, then confirm whether it is resolved.", "Record the objection type so patterns can be fixed at the source."],
    whatNotToDo: ["Do not answer a price objection with more features.", "Do not move to a new option without closing the old objection."],
    problemsThatCanOccur: ["The stated objection hides the real one — usually money or a person.", "Objection handled verbally and never recorded."],
    branches: [
      ["Price objection", "Reframe on total cost including deposit and commute, then offer a genuine alternative."],
      ["Trust objection", "Send verifiable proof: agreement, previous tenants, our process."],
    ],
    doneWhen: "The objection is answered in writing and its status is recorded.",
    quickNotes: ["Said deposit is too high, ignored"],
  }),
  L({
    id: "discount-unapproved", group: "money", label: "A discount or waiver was offered without approval", short: "Unapproved discount",
    severity: "critical", slaHours: 1,
    why: "Unapproved discounts break owner relationships, distort margins and set a precedent the customer will quote back to us later.",
    howToExecute: ["Quote the exact message where the discount was offered.", "Escalate to the manager before saying anything further to the customer.", "If it cannot be honoured, the manager — not the agent — resets expectations."],
    whatNotToDo: ["Do not honour it quietly to avoid a conversation.", "Do not withdraw it abruptly in chat without a plan."],
    problemsThatCanOccur: ["The customer screenshots and shares the offer.", "The owner learns from the customer, not from us."],
    branches: [
      ["Within the approved band", "Approve, record it, and move on."],
      ["Outside the band", "Manager calls the customer personally with an alternative of equal value."],
    ],
    doneWhen: "The discount is either approved and recorded, or reset by a manager.",
    quickNotes: ["Offered 1 month free without asking anyone"],
  }),
  L({
    id: "token-stalled", group: "money", label: "Token payment agreed but not collected", short: "Token stalled",
    severity: "critical", slaHours: 2,
    why: "Between 'yes' and 'paid' is where deals evaporate. Every hour without a payment link is an hour for someone to talk them out of it.",
    howToExecute: ["Send the payment link or details immediately, in the same thread.", "State exactly what the token secures and until when.", "Follow up in two hours with a status check, not a nag."],
    whatNotToDo: ["Do not send bank details without an explanation of what is being secured.", "Do not let a verbal yes sit overnight."],
    problemsThatCanOccur: ["Payment friction — app limits, wrong details, work hours.", "Family intervenes between yes and payment."],
    branches: [
      ["Payment fails technically", "Offer an alternative method within minutes."],
      ["They delay by a day", "Get the date in writing and hold the room explicitly."],
    ],
    doneWhen: "Payment is received, or a written commitment with a date and a hold exists.",
    quickNotes: ["Said yes yesterday, no payment link sent"],
  }),
  L({
    id: "agreement-pending", group: "money", label: "Agreement or documentation is stuck", short: "Paperwork stuck",
    severity: "action", slaHours: 8,
    why: "Paid customers who cannot complete paperwork churn back out, and refunds cost far more than the booking earned.",
    howToExecute: ["List exactly which document is missing and from whom.", "Chase both sides with a deadline the same day.", "Escalate after 24 hours rather than waiting quietly."],
    whatNotToDo: ["Do not blame the customer for a slow owner.", "Do not let the move-in date arrive with paperwork unsigned."],
    problemsThatCanOccur: ["Documents from another city or country.", "The owner wants terms not previously disclosed."],
    branches: [
      ["Customer-side delay", "Offer to collect digitally and walk them through it on a call."],
      ["Owner-side delay", "Escalate to the supply team the same day."],
    ],
    doneWhen: "The missing document is received or a dated commitment exists from the responsible side.",
    quickNotes: ["Paid 3 days ago, agreement not started"],
  }),
  L({
    id: "refund-risk", group: "money", label: "This booking is at risk of cancellation or refund", short: "Cancellation risk",
    severity: "critical", slaHours: 2,
    why: "A cancellation costs the booking, the owner relationship and often a public review. Catching the wobble a day early is usually enough to save it.",
    howToExecute: ["Name the signal you saw: a complaint, a delayed document, a changed date, a family objection.", "Call the customer, not the owner, first.", "Bring a concrete remedy to the call, not just sympathy."],
    whatNotToDo: ["Do not go silent hoping the wobble passes.", "Do not promise a refund before the manager decides."],
    problemsThatCanOccur: ["The property failed the expectation set in chat.", "A competitor re-entered with a better offer."],
    branches: [
      ["Cause is the property", "Offer a transfer to an equivalent unit before discussing a refund."],
      ["Cause is personal", "Offer a date shift or a hold instead of cancellation."],
    ],
    doneWhen: "A manager is informed and a written remedy has been offered to the customer.",
    quickNotes: ["Customer unhappy after move-in, hinting at leaving"],
  }),

  // ───────────────────── CHAT QUALITY & CONDUCT ─────────────────────
  L({
    id: "template-spam", group: "quality", label: "Templates pasted without personalisation", short: "Template dump",
    severity: "coaching", slaHours: 8,
    why: "Customers recognise a template instantly and reply to it at a fraction of the rate. Templates are a starting point, not the message.",
    howToExecute: ["Point at the pasted block in the note.", "Rewrite it with their area, date, budget and the property they actually asked about.", "Keep the structure, change the specifics."],
    whatNotToDo: ["Do not send the same block to several leads in the same minute.", "Do not leave placeholder text in the message."],
    problemsThatCanOccur: ["The template contains outdated prices.", "Agents keep private templates nobody reviews."],
    branches: [
      ["Template is good but generic", "Personalise the first and last line."],
      ["Template is wrong or outdated", "Fix it in the shared library, not just in this chat."],
    ],
    doneWhen: "A personalised message replaces the template in the thread.",
    quickNotes: ["Same 8-line block sent to 4 leads"],
  }),
  L({
    id: "language-mismatch", group: "quality", label: "We are replying in the wrong language", short: "Language mismatch",
    severity: "action", slaHours: 6,
    why: "A customer writing in Hindi or Kannada and receiving formal English will disengage politely and go elsewhere. Language match is a trust signal.",
    howToExecute: ["Match the language and register of their last three messages.", "If nobody on the thread speaks it, reassign to someone who does.", "Record the language preference."],
    whatNotToDo: ["Do not machine-translate long paragraphs.", "Do not switch language mid-negotiation."],
    problemsThatCanOccur: ["Mixed-language households where the payer prefers another language.", "Voice notes in a language the agent cannot follow."],
    branches: [
      ["Nobody available in that language", "Move to a voice call with a colleague who speaks it."],
      ["They switch to English themselves", "Follow their lead."],
    ],
    doneWhen: "The thread is running in the customer's preferred language.",
    quickNotes: ["Customer writes Hindi, we keep replying in English"],
  }),
  L({
    id: "tone-problem", group: "quality", label: "Tone was rude, blunt or dismissive", short: "Tone problem",
    severity: "critical", slaHours: 2,
    why: "One dismissive line ends a deal and can end up on a review site. Tone is not a soft issue — it is a revenue and brand issue.",
    howToExecute: ["Quote the exact line in the note; do not paraphrase.", "Coach privately the same day, before the next shift.", "If the customer is still active, a senior person repairs the thread personally."],
    whatNotToDo: ["Do not coach in a group channel.", "Do not ask the same agent to apologise if they are still frustrated."],
    problemsThatCanOccur: ["The agent was provoked, and coaching without acknowledging that breeds resentment.", "The customer already screenshotted it."],
    branches: [
      ["Customer reacted", "Senior repair call today plus a written apology."],
      ["Customer did not react", "Coach privately and keep watching that agent's threads for a week."],
    ],
    doneWhen: "The agent has been coached and, if needed, the thread has been repaired by a senior.",
    quickNotes: ["Replied 'I already told you' to a repeated question"],
  }),
  L({
    id: "over-promising", group: "quality", label: "We over-promised something we cannot deliver", short: "Over-promise",
    severity: "critical", slaHours: 2,
    why: "Over-promising converts today and cancels next week, with a refund and a bad review attached. It also poisons the owner relationship.",
    howToExecute: ["Quote the promise.", "Establish what is actually possible with the owner.", "Reset expectations in writing before the customer acts on the promise."],
    whatNotToDo: ["Do not hope it will be forgotten.", "Do not reset expectations only verbally."],
    problemsThatCanOccur: ["The promise is already priced into their decision.", "The agent repeats the pattern because it hits short-term targets."],
    branches: [
      ["Promise can be honoured at a cost", "Get manager approval and honour it."],
      ["It cannot", "Manager resets with the customer and offers an alternative of equal value."],
    ],
    doneWhen: "Reality is documented in the thread and the customer has acknowledged it.",
    quickNotes: ["Promised parking that does not exist"],
  }),
  L({
    id: "voice-note-only", group: "quality", label: "Key information exists only in a call or voice note", short: "Nothing in writing",
    severity: "action", slaHours: 6,
    why: "If the price, the date or the promise exists only in audio, the next person on the lead is working blind and the customer can claim anything.",
    howToExecute: ["Summarise the call in the thread in three lines: what was agreed, what is pending, what is next.", "Put the numbers in writing.", "Copy the same summary onto the lead record."],
    whatNotToDo: ["Do not rely on the customer to remember the terms.", "Do not write the summary a day later from memory."],
    problemsThatCanOccur: ["Disputes over what was agreed.", "Reassignment loses the entire context."],
    branches: [
      ["Commercial terms were discussed", "Written confirmation is mandatory before proceeding."],
      ["Only rapport was built", "One line on the record is enough."],
    ],
    doneWhen: "A written summary of the call exists in the thread and on the record.",
    quickNotes: ["Everything agreed on a call, nothing written"],
  }),

  // ───────────────────────── CRM HYGIENE & DATA ─────────────────────────
  L({
    id: "duplicate-lead", group: "data", label: "This looks like a duplicate lead", short: "Duplicate",
    severity: "action", slaHours: 4,
    why: "Duplicates mean two people calling the same customer with two different prices. It looks unprofessional and it corrupts every conversion metric we have.",
    howToExecute: ["Search by phone and by name, and link the records in the note.", "Decide one owner — normally whoever spoke to the customer first.", "Merge the history so nothing is lost, then close the duplicate."],
    whatNotToDo: ["Do not delete the duplicate before copying its history.", "Do not leave both open 'just in case'."],
    problemsThatCanOccur: ["The two records have conflicting requirements — the newer one usually wins.", "Both owners have already contacted the customer."],
    branches: [
      ["Both contacted the customer", "Agree one owner and send a single clarifying message from that person."],
      ["Different requirements in each", "Keep the newer requirement and note the change."],
    ],
    doneWhen: "One live record remains, with the merged history and a single owner.",
    quickNotes: ["Same number appears twice with different owners"],
  }),
  L({
    id: "wrong-owner", group: "data", label: "Assigned to the wrong person or zone", short: "Wrong owner",
    severity: "action", slaHours: 4,
    why: "A lead in the wrong zone gets slow, generic service because the owner does not know the inventory or the streets.",
    howToExecute: ["Confirm the customer's actual anchor area.", "Reassign to the zone owner with a two-line handover of what has happened so far.", "Introduce the new owner in the thread so the customer is not surprised."],
    whatNotToDo: ["Do not reassign silently mid-negotiation.", "Do not reassign to someone already at capacity."],
    problemsThatCanOccur: ["The customer has built rapport with the current owner.", "Handover loses context and the customer repeats themselves."],
    branches: [
      ["Strong rapport already exists", "Keep the owner and give them zone support instead."],
      ["Little contact so far", "Reassign now with a clean handover."],
    ],
    doneWhen: "The lead sits with the right owner and a handover note exists.",
    quickNotes: ["Whitefield lead sitting with a South zone agent"],
  }),
  L({
    id: "stage-wrong", group: "data", label: "Pipeline stage does not match reality", short: "Wrong stage",
    severity: "coaching", slaHours: 8,
    why: "If stages are wrong, every forecast, every capacity decision and every review is wrong. Optimistic stages are the most expensive kind of lie in a CRM.",
    howToExecute: ["Read the last real interaction and set the stage that matches it.", "Move it down if needed — accuracy beats optics.", "Add the evidence line that justifies the stage."],
    whatNotToDo: ["Do not park leads in a hot stage to protect a number.", "Do not skip stages because a booking feels likely."],
    problemsThatCanOccur: ["Agents are measured on stage counts, which drives inflation.", "Bulk stage updates hide real changes."],
    branches: [
      ["Stage is ahead of reality", "Move it back and inform the manager."],
      ["Stage is behind reality", "Move it forward and set the closing action."],
    ],
    doneWhen: "The stage matches the last real interaction and has an evidence line.",
    quickNotes: ["Marked 'negotiation', last contact was a first hello"],
  }),
  L({
    id: "fields-empty", group: "data", label: "Core fields are empty on an active lead", short: "Empty record",
    severity: "action", slaHours: 8,
    why: "An empty record means the knowledge lives in one person's head. The moment they are on leave, the lead is effectively new again.",
    howToExecute: ["Fill budget, move-in, area, occupancy and source from the thread — most of it is already written there.", "Where the thread does not answer it, ask one question.", "Do not invent values to clear the flag."],
    whatNotToDo: ["Do not fill fields with placeholder values.", "Do not copy the same defaults across leads."],
    problemsThatCanOccur: ["Fields get filled but never updated when things change.", "Data entry replaces actual selling."],
    branches: [
      ["The thread contains the answers", "Transcribe them now — five minutes of work."],
      ["It does not", "Ask one question, the highest-value gap first."],
    ],
    doneWhen: "The core fields are populated from evidence, not guesses.",
    quickNotes: ["Active for a week, budget and date fields blank"],
  }),
  L({
    id: "source-unknown", group: "data", label: "Lead source is missing or wrong", short: "Source unknown",
    severity: "coaching", slaHours: 12,
    why: "If we do not know where leads come from, we cannot tell which spend works. Wrong source data quietly wastes marketing budget every month.",
    howToExecute: ["Check the entry point: campaign number, portal, referral, walk-in.", "Set it on the record.", "If it truly cannot be determined, mark unknown rather than guessing."],
    whatNotToDo: ["Do not default everything to WhatsApp.", "Do not overwrite an existing correct source."],
    problemsThatCanOccur: ["Several campaigns share one number.", "Referrals get logged as organic and the referrer is never thanked."],
    branches: [
      ["It is a referral", "Record the referrer and trigger the thank-you."],
      ["Genuinely unknown", "Mark unknown, and fix the capture at the source."],
    ],
    doneWhen: "Source is set truthfully on the record.",
    quickNotes: ["Source blank on a paid campaign lead"],
  }),

  // ───────────────── RISK, ESCALATION & COMPLIANCE ─────────────────
  L({
    id: "complaint-risk", group: "risk", label: "Customer is unhappy — complaint risk", short: "Complaint risk",
    severity: "critical", slaHours: 1,
    why: "Unhappy customers write reviews that cost far more than the deal. Speed and ownership defuse almost all of them; silence guarantees escalation.",
    howToExecute: ["Call within the hour — do not handle a complaint in chat.", "Acknowledge the specific failure without excuses.", "Offer one concrete remedy and a time, then follow up when you said you would."],
    whatNotToDo: ["Do not argue about who is right.", "Do not let the person who caused it handle it alone."],
    problemsThatCanOccur: ["The complaint is about the owner and we have limited control.", "The remedy is promised and missed, doubling the anger."],
    branches: [
      ["Our failure", "Own it fully and remedy today."],
      ["Owner's failure", "Represent the customer to the owner and keep the customer informed hourly."],
    ],
    doneWhen: "A call happened, a remedy is agreed, and a manager is aware.",
    quickNotes: ["Angry about a wasted visit"],
  }),
  L({
    id: "escalate-now", group: "risk", label: "Escalate to a manager now", short: "Escalate",
    severity: "critical", slaHours: 1,
    why: "Some situations are above the floor's authority — refunds, legal threats, safety, media. Delaying escalation turns a decision into a crisis.",
    howToExecute: ["Write the situation in five lines: what happened, what the customer wants, what we can do, what we cannot, and what you recommend.", "Tag the manager and confirm they have seen it.", "Do not send anything further to the customer until they respond."],
    whatNotToDo: ["Do not escalate without a recommendation.", "Do not keep negotiating while the escalation is open."],
    problemsThatCanOccur: ["Manager unavailable — have a named backup.", "Escalation used to avoid difficult but normal conversations."],
    branches: [
      ["Manager unreachable in 30 minutes", "Go to the named backup, do not wait."],
      ["Customer is public-facing angry", "Escalate and pause all templated messaging on the thread."],
    ],
    doneWhen: "A manager has acknowledged and a decision is recorded.",
    quickNotes: ["Threatening to post publicly"],
  }),
  L({
    id: "pii-exposure", group: "risk", label: "Personal data was shared unsafely", short: "Data exposure",
    severity: "critical", slaHours: 1,
    why: "Sharing a customer's number, documents or photos with the wrong person is a privacy breach with legal and reputational consequences.",
    howToExecute: ["Identify exactly what was shared and with whom.", "Delete or recall where possible and inform the manager immediately.", "Re-brief the agent on what may be shared with owners."],
    whatNotToDo: ["Do not hide it because it seems minor.", "Do not forward ID documents in group chats."],
    problemsThatCanOccur: ["Owner circulates the customer's number to other agents.", "Documents sit in an unmanaged group."],
    branches: [
      ["Shared with an owner", "Instruct deletion in writing and confirm."],
      ["Shared in a group", "Escalate immediately; assume it cannot be recalled."],
    ],
    doneWhen: "The exposure is contained, recorded, and the manager is informed.",
    quickNotes: ["Aadhaar forwarded into an owners group"],
  }),
  L({
    id: "suspicious-lead", group: "risk", label: "Lead looks fake, spam or fraudulent", short: "Suspicious",
    severity: "action", slaHours: 4,
    why: "Fake leads eat capacity that should go to real customers, and some are active scam attempts against owners or us.",
    howToExecute: ["List the signals: mismatched details, refusal to call, unusual payment requests, copy-paste messages.", "Verify with one voice call before doing anything else.", "If confirmed, mark and close it — do not just ignore it."],
    whatNotToDo: ["Do not share owner contact details before verification.", "Do not accuse the person; verify quietly."],
    problemsThatCanOccur: ["A genuine customer is wrongly flagged — always verify by voice.", "The same pattern repeats across many leads and needs a source fix."],
    branches: [
      ["Verified genuine", "Remove the flag and continue normally."],
      ["Confirmed fake", "Close with a reason and report the pattern."],
    ],
    doneWhen: "The lead is verified or closed with a documented reason.",
    quickNotes: ["Wants owner details, refuses a call"],
  }),
  L({
    id: "safety-concern", group: "risk", label: "Safety concern for staff or customer", short: "Safety",
    severity: "critical", slaHours: 1,
    why: "Nothing in the funnel outranks physical safety. Late-night solo visits, hostile behaviour and unsafe buildings must stop the process immediately.",
    howToExecute: ["Stop the activity first, ask questions after.", "Inform the manager immediately with the specifics.", "Reschedule with a companion, in daylight, or cancel entirely."],
    whatNotToDo: ["Do not send anyone alone to a flagged property.", "Do not weigh a booking against a safety risk."],
    problemsThatCanOccur: ["Pressure to hit targets overrides the concern.", "The concern is not recorded and repeats next month."],
    branches: [
      ["Concern about the property", "Suspend the property until reviewed."],
      ["Concern about the customer", "Move all contact to office hours and record everything in writing."],
    ],
    doneWhen: "The activity is stopped, the manager knows, and the concern is recorded on the record.",
    quickNotes: ["Late-night solo visit requested at an unverified property"],
  }),

  // ───────────────────────── LIFECYCLE & REVIVAL ─────────────────────────
  L({
    id: "future-movein", group: "lifecycle", label: "Genuine lead but the move-in is far out", short: "Future move-in",
    severity: "coaching", slaHours: 24,
    why: "Chasing a 60-day lead daily burns the relationship and the agent's hours. Parked properly with a dated wake-up, the same lead converts easily later.",
    howToExecute: ["Confirm the month and the trigger event — lease end, joining date, exam, notice period.", "Set a wake-up two weeks before the trigger.", "Send value at a low cadence in between, never a nudge."],
    whatNotToDo: ["Do not keep them in the daily queue.", "Do not forget them entirely — parked is not dead."],
    problemsThatCanOccur: ["Their date moves earlier and nobody notices.", "Parked leads never wake up because the reminder is not dated."],
    branches: [
      ["Date moves closer", "Pull them back into the active queue immediately."],
      ["Trigger passes silently", "One re-qualification message, then close honestly."],
    ],
    doneWhen: "A dated wake-up exists and the cadence is set to nurture.",
    quickNotes: ["Moving in 3 months, being chased daily"],
  }),
  L({
    id: "ghosted", group: "lifecycle", label: "Ghosted after strong interest", short: "Ghosted",
    severity: "action", slaHours: 12,
    why: "A lead that engaged and then vanished usually has a specific reason — money, a person, or a competitor. The reason is recoverable; the silence is not, if we let it sit.",
    howToExecute: ["Send one honest close-the-loop message that makes a 'no' easy to send.", "Change channel and hour before you change the words.", "If they answer with a reason, record it — it is worth more than the lead."],
    whatNotToDo: ["Do not guilt them.", "Do not keep the thread on a daily cadence."],
    problemsThatCanOccur: ["They already booked elsewhere and feel awkward saying so.", "Their number changed."],
    branches: [
      ["They reply with a reason", "Record it and either handle the objection or close cleanly."],
      ["Total silence after two attempts", "Move to revival and set a 30-day wake-up."],
    ],
    doneWhen: "A close-the-loop message is sent and the lead is either revived or moved to nurture.",
    quickNotes: ["Was ready to book, silent for 5 days"],
  }),
  L({
    id: "lost-reason-missing", group: "lifecycle", label: "Lead was closed without a real reason", short: "No lost reason",
    severity: "action", slaHours: 8,
    why: "'Not interested' teaches us nothing. Without the real reason we cannot fix pricing, inventory or process, and we repeat the loss a hundred times.",
    howToExecute: ["Re-read the thread and find the actual blocker.", "Record the reason category plus one specific sentence.", "If the reason is fixable, reopen the lead instead of closing it."],
    whatNotToDo: ["Do not use 'not interested' as a default.", "Do not close a lead that has never been contacted."],
    problemsThatCanOccur: ["Agents close leads to clean their queue before review.", "The real reason is embarrassing to record."],
    branches: [
      ["Reason is price or inventory", "Route it to the supply team as a signal, not just a closure."],
      ["Reason is our service", "Route it to coaching and to the L1 review."],
    ],
    doneWhen: "A specific, categorised lost reason is on the record.",
    quickNotes: ["Closed as 'not interested' after one message"],
  }),
  L({
    id: "revival-candidate", group: "lifecycle", label: "Old lost lead worth reviving now", short: "Revive",
    severity: "coaching", slaHours: 24,
    why: "Rental demand is cyclical. A lead lost on price in March is a strong lead in June when their lease ends or their salary changes — and we already know everything about them.",
    howToExecute: ["State the trigger that makes now the right time: new inventory, price drop, their lease cycle, a new area.", "Open with the trigger, not with 'checking in'.", "Re-qualify in one question — their situation has changed."],
    whatNotToDo: ["Do not revive with the same option that lost the deal.", "Do not mass-revive an entire lost list in one day."],
    problemsThatCanOccur: ["They already rented and feel spammed.", "Their old requirement is completely stale."],
    branches: [
      ["Lost on price", "Revive only when a genuinely cheaper or better-value option exists."],
      ["Lost on availability", "Revive the moment the same building has a unit."],
    ],
    doneWhen: "A trigger-based revival message is sent and the outcome is recorded.",
    quickNotes: ["Lost on price in March, new cheaper unit in the same lane"],
  }),
  L({
    id: "referral-opportunity", group: "lifecycle", label: "Happy customer — ask for a referral", short: "Referral",
    severity: "positive", slaHours: 24,
    why: "Referred leads convert far better and cost nothing. The window is the first two weeks after a good move-in, and it closes quickly.",
    howToExecute: ["Wait until they are settled, then ask once, specifically: 'anyone in your office or batch looking?'.", "Make it easy — offer to message the friend directly.", "Record the referrer so the reward and the thank-you actually happen."],
    whatNotToDo: ["Do not ask before the move-in is smooth.", "Do not ask repeatedly."],
    problemsThatCanOccur: ["Asking too soon reads as transactional.", "Referral rewards are promised and never paid, which kills the channel."],
    branches: [
      ["Move-in went well", "Ask now, with a specific prompt."],
      ["There were problems", "Fix them first; do not ask."],
    ],
    doneWhen: "The ask was made and the response — including a no — is recorded.",
    quickNotes: ["Great move-in feedback, never asked for a referral"],
  }),

  // ─────────────────────────── RECOGNITION ───────────────────────────
  L({
    id: "great-question", group: "positive", label: "Excellent qualifying question — copy this", short: "Great question",
    severity: "positive", slaHours: 24,
    why: "Question quality is the most teachable skill on the floor and the one with the biggest conversion effect. Marking a good one on a real chat spreads it faster than training.",
    howToExecute: ["Quote the exact question in the note.", "Explain in one line why it worked — what it unlocked.", "Add it to the shared question library."],
    whatNotToDo: ["Do not praise vaguely.", "Do not turn it into a mandatory script."],
    problemsThatCanOccur: ["It becomes a template and loses its effect.", "The same person is always the example."],
    branches: [["It is repeatable", "Add it to the library."], ["It worked because of context", "Praise it, do not systematise it."]],
    doneWhen: "The question is in the shared library with a one-line reason.",
    quickNotes: ["'This week or next month?' unlocked the whole brief"],
  }),
  L({
    id: "great-recovery", group: "positive", label: "Great recovery from a bad situation", short: "Great recovery",
    severity: "positive", slaHours: 24,
    why: "Recovery skill — after a no-show, a wrong price, an angry message — is rarer and more valuable than a clean win. It should be studied, not just applauded.",
    howToExecute: ["Describe the situation and the exact move that turned it.", "Share it as a case in the huddle.", "Add the recovery pattern to the playbook."],
    whatNotToDo: ["Do not praise the recovery while ignoring the cause.", "Do not share customer identity."],
    problemsThatCanOccur: ["Teams start valuing recoveries over prevention.", "The cause is never fixed."],
    branches: [["Cause was systemic", "Fix the system and praise the recovery."], ["Cause was personal", "Coach the cause privately, praise the recovery publicly."]],
    doneWhen: "The recovery pattern is written into the playbook.",
    quickNotes: ["Turned an angry no-show into a same-day visit"],
  }),
  L({
    id: "speed-example", group: "positive", label: "Textbook speed — use as the standard", short: "Speed example",
    severity: "positive", slaHours: 24,
    why: "Speed standards are believed when the floor sees one of their own doing it, not when a target is announced in a meeting.",
    howToExecute: ["Record the actual response times.", "Show the thread as the benchmark in the huddle.", "Set it as the zone's standard for the week."],
    whatNotToDo: ["Do not praise speed that came with sloppy content.", "Do not make it a stick to beat others with."],
    problemsThatCanOccur: ["Agents optimise for speed and drop quality.", "Fast replies with no substance start appearing."],
    branches: [["Speed and quality both high", "Make it the standard."], ["Fast but thin", "Coach quality before celebrating speed."]],
    doneWhen: "The example is shared and the standard is stated.",
    quickNotes: ["Replied in 40 seconds with a real option"],
  }),
];
