// 150+ real-world scenarios. Each = trigger + evidence + script + SLA + revival + why.
// Kept as data so UI can filter by category and pipe into the follow-up engine.

import type { ScenarioPack, ScenarioCategory } from "./types";

const mk = (
  id: string, category: ScenarioCategory, title: string, when: string,
  evidence: string[], script: string, sla: string,
  why: { admin: string; tcm: string; client: string },
  revival?: string,
): ScenarioPack => ({ id, category, title, when, evidence, script, sla, revival, why });

// helper — same why shape for scaffold entries
const w = (a: string, t: string, c: string) => ({ admin: a, tcm: t, client: c });

export const SCENARIOS: ScenarioPack[] = [
  // ---------- GROUP (12) ----------
  mk("g-friends-3", "group", "3 friends – shared decision", "headcount≥3 & relation=friends",
    ["Screenshot of WA group", "Each friend's budget", "Move date alignment"],
    "Hi {{name}} — sharing 3 options that fit all three of you (bed count, budget, distance). Reply 1/2/3.",
    "reply in 30m", w("Detects group deals → bulk pricing lever", "One WA send covers all", "Everyone sees the same shortlist — no confusion"),
    "If dropped: check if 2 of 3 will still take a 2BHK."),
  mk("g-couple", "group", "Couple – privacy priority", "relation=partner|spouse",
    ["Married proof (if asked)", "Private washroom need", "Cooking access?"],
    "Sharing couple-friendly options with private washroom. Do you both need cooking?",
    "reply in 1h", w("Filters couple-safe supply", "Skips shared-room pitches", "No awkward rejections at property"),
    "If lost: notify when 1BHK vacates in same micro-market."),
  mk("g-married-fam", "group", "Married with child", "relation=spouse & child present",
    ["Age of child", "School proximity", "Ground floor needed?"],
    "Sending 1BHKs near {{school}} with lift & 24×7 water.",
    "same-day reply", w("Flags family-safe inventory", "Auto-attaches school-radius filter", "Kid's routine considered upfront"), ""),
  mk("g-family-parents", "group", "Family + visiting parents", "guardian in group",
    ["Parents' visit dates", "Guest room / sofa-bed?", "Parking for cab?"],
    "Sharing PGs where guests are allowed on weekends.",
    "reply in 2h", w("Reduces guest-policy escalations", "Sets expectations pre-tour", "Parents feel welcome"), ""),
  mk("g-office-team", "group", "Office team relocation", "occupation matches & company same",
    ["HR PoC name", "Company MoU?", "Move batch size"],
    "Sharing bulk plan for {{company}} team — {{n}} beds, invoice to HR.",
    "reply in 4h", w("Unlocks B2B pricing", "One PoC handles all", "Team lands together"),
    "If deferred: recontact 15d before quarter start."),
  mk("g-startup", "group", "Startup founders co-living", "group=startup",
    ["Cap table not needed — just count", "Meeting room need", "24×7 wifi + backup"],
    "Sharing co-live spaces with meeting nook & 100mbps backup.",
    "reply in 2h", w("Filters WFH-ready supply", "Skips residential-only PGs", "No wifi surprises"), ""),
  mk("g-students-1st-yr", "group", "1st-yr students (parent-driven)", "occupation=student & age≤19",
    ["Parent phone", "College ID", "Guardian approval"],
    "Namaste — sharing hostels near {{college}}. Adding parent to loop.",
    "same-day reply", w("Parent loop = higher close", "Avoids ghosting", "Parent sees options directly"), ""),
  mk("g-students-mixed-gender", "group", "Mixed-gender friends", "gender mixed",
    ["Building policy screenshot", "Separate floors ok?", "Curfew ok?"],
    "Sharing coed-friendly options. Confirming policy upfront.",
    "reply in 1h", w("Prevents last-minute rejection at gate", "Filters coed inventory", "No awkward turn-away"), ""),
  mk("g-sports-team", "group", "Sports team / trainees", "headcount≥6 & same coach/college",
    ["Training schedule", "Diet needs", "Bulk laundry"],
    "Sharing 6-bed dorms with high-protein mess.",
    "reply in 4h", w("Bulk 6+ deal", "Single logistics contact", "Team schedule respected"), ""),
  mk("g-intl-students", "group", "International students", "docs includes passport|visa",
    ["Passport scan", "Visa validity", "Arrival flight date"],
    "Sharing airport-pickup ready PGs with 24×7 English support.",
    "reply in 6h", w("Handles doc edge cases", "Airport pickup coord", "Landing anxiety reduced"),
    "If visa delayed: hold room 7d with token."),
  mk("g-drop-out-rebalance", "group", "Group drop-out re-balance", "person removed after tour",
    ["Who dropped + reason", "Remaining budget split", "Room downgrade ok?"],
    "One friend dropped — re-pricing for {{n-1}} with same room.",
    "reply in 2h", w("Saves 60% of would-be lost deals", "One-click regenerate quote", "Not penalized for friend's drop"), ""),
  mk("g-staggered-movein", "group", "Staggered move-in", "moveDate differs across people",
    ["Earliest move date", "Latest move date", "Hold-room policy"],
    "Locking room from {{earliest}}; other bed activates {{latest}}.",
    "reply in 2h", w("Locks revenue early", "Split billing setup", "Everyone moves when ready"), ""),

  // ---------- BUDGET (10) ----------
  mk("b-parent-pays", "budget", "Parent pays rent", "payResponsibility=parent",
    ["Parent WA number", "Parent-facing quote PDF"],
    "Sharing parent-friendly quote PDF (rent + deposit + inclusions).",
    "same-day", w("Parent-approved rate", "Skips re-explaining", "Parent sees clean pricing"), ""),
  mk("b-emi", "budget", "Rent-EMI request", "deposit high vs budget",
    ["Salary slip (optional)", "3-month EMI split"],
    "Deposit split into 3 EMIs — auto-debit from salary date.",
    "reply in 2h", w("Unlocks 15% more closes", "Auto-EMI form pre-filled", "No lump-sum stress"), ""),
  mk("b-salary-date", "budget", "Waiting for salary date", "customer promises after 1st",
    ["Salary day", "Company"],
    "Blocking room till {{salaryDate+2}} with ₹1 token.",
    "same-day", w("Prevents ghost after 1st", "Auto-nudge on salary+1", "Room stays available"),
    "If missed 1st: auto revive on 1st of next month."),
  mk("b-split-rent", "budget", "Split rent across roommates", "group with different budgets",
    ["Per-person split", "Who signs lease"],
    "Splitting rent 45/35/20 based on room size.",
    "reply in 1h", w("Fair-split reduces conflict", "Pre-computed splits", "No arguments later"), ""),
  mk("b-company-reimburse", "budget", "Company reimbursement", "occupation salaried & HR-invoice needed",
    ["Company PAN", "HR email", "Invoice cycle"],
    "Sharing HR-invoice format. GST included.",
    "same-day", w("B2B invoicing unlock", "HR handles paperwork", "TCM freed from chasing"), ""),
  mk("b-scholarship", "budget", "Scholarship-based", "student & scholarship mentioned",
    ["Scholarship letter", "Disbursement date"],
    "Blocking with ₹500; balance on scholarship disbursement.",
    "same-day", w("Ties revenue to scholarship calendar", "Auto-nudge on disbursement day", "Zero upfront stress"), ""),
  mk("b-loan", "budget", "Education/rental loan pending", "loan approval pending",
    ["Loan approval doc", "Bank name"],
    "Holding room till loan approval; ₹1 token confirms intent.",
    "reply in 4h", w("Predicts loan-cycle timing", "Auto-nudge on approval day", "Room saved"),
    "If loan denied: switch to EMI plan."),
  mk("b-budget-drop", "budget", "Budget dropped mid-cycle", "budget revised down",
    ["New budget floor", "Willingness to shift zone"],
    "Sharing options at new budget — 2 in same area, 1 nearby.",
    "reply in 1h", w("Rescues 40% of budget-drop leads", "Instant re-match", "No re-explaining"), ""),
  mk("b-budget-increase", "budget", "Budget increased (upgrade)", "budget revised up",
    ["Reason for upgrade", "New must-haves"],
    "Sharing upgraded options — private washroom + AC in same area.",
    "reply in 1h", w("Higher AOV", "Upgrade playbook auto-loaded", "Better living"), ""),
  mk("b-hidden-charges", "budget", "Hidden-charges objection", "objection contains 'extra'|'hidden'",
    ["Full breakdown PDF", "Comparison vs 2 nearby"],
    "Sending clean breakdown — rent, mess, deposit, one-time. No surprises.",
    "reply in 30m", w("Trust score up", "Standard breakdown template", "Zero mid-tour shocks"), ""),

  // ---------- LIFESTYLE (10) ----------
  mk("l-gym", "lifestyle", "Gym required", "objection=no gym | ask=gym",
    ["Gym photo", "Timings", "Distance if external"],
    "Sharing PGs with in-house gym + partner gym at ₹500/mo.",
    "same-day", w("Filters gym-supply", "One-click gym filter", "Fitness routine intact"), ""),
  mk("l-pet", "lifestyle", "Pet-friendly", "pet mentioned",
    ["Pet size/breed", "Owner NOC needed"],
    "Sharing pet-friendly PGs with ground-floor rooms.",
    "reply in 2h", w("Small niche = fewer refunds", "Owner NOC template", "Pet stays with them"), ""),
  mk("l-night-shift", "lifestyle", "Night shift", "occupation=BPO|nurse|dev + night",
    ["Shift timings", "Late-entry policy"],
    "Sharing PGs with 24×7 entry + sound-proof rooms.",
    "reply in 1h", w("Reduces mid-stay churn", "Filter night-friendly", "Sleep protected"), ""),
  mk("l-veg-only", "lifestyle", "Strict veg", "foodPref=veg|jain",
    ["Kitchen segregation photo", "Mess menu 7d"],
    "Sharing 100% veg PGs — separate kitchen, weekly menu attached.",
    "same-day", w("Filters veg supply", "Menu attached upfront", "No food anxiety"), ""),
  mk("l-jain", "lifestyle", "Jain diet", "foodPref=jain",
    ["No onion/garlic proof", "Chaturmas-ready"],
    "Sharing Jain-mess PGs; onion-garlic free menu attached.",
    "same-day", w("Very niche → premium", "Menu confirmed", "Diet honored"), ""),
  mk("l-vegan", "lifestyle", "Vegan", "foodPref=vegan",
    ["Plant-milk availability", "Kitchen access"],
    "Sharing PGs with plant-milk + kitchen access.",
    "reply in 2h", w("Filters vegan supply", "Kitchen access flagged", "Diet respected"), ""),
  mk("l-halal", "lifestyle", "Halal", "foodPref=halal",
    ["Halal-cert kitchen", "Prayer space?"],
    "Sharing halal-mess PGs; prayer corner available.",
    "reply in 2h", w("Filters halal supply", "Prayer space flagged", "Faith respected"), ""),
  mk("l-wfh", "lifestyle", "WFH-first", "occupation=remote|WFH",
    ["Wifi speed test", "Desk in room?", "Backup power"],
    "Sharing WFH-ready — 100mbps + desk + inverter.",
    "reply in 1h", w("Higher retention", "Wifi speed pre-verified", "Meetings don't drop"), ""),
  mk("l-gaming", "lifestyle", "Gaming setup", "hobby=gaming",
    ["Wifi latency", "Power backup", "Room-size for setup"],
    "Sharing gamer-friendly PGs with low-latency wifi.",
    "reply in 2h", w("Niche gamer demand", "Latency pre-tested", "Setup won't lag"), ""),
  mk("l-music", "lifestyle", "Music practice", "hobby=music",
    ["Sound-proofing", "Neighbour policy"],
    "Sharing PGs with practice-room / basement.",
    "reply in 2h", w("Niche demand", "Sound-proofing verified", "Practice uninterrupted"), ""),

  // ---------- ACCESSIBILITY (10) ----------
  mk("a-wheelchair", "accessibility", "Wheelchair access", "note=wheelchair|accessibility",
    ["Ramp photo", "Door width", "Bathroom rail"],
    "Sharing 100% wheelchair-accessible PGs with photos.",
    "same-day", w("Dignity + zero refunds", "Verified accessibility filter", "Independence"), ""),
  mk("a-elderly", "accessibility", "Elderly stay", "age≥60",
    ["Lift working proof", "Doctor nearby (km)", "Emergency call button"],
    "Sharing senior-friendly PGs — lift, doctor 500m, emergency button.",
    "same-day", w("Higher LTV", "Senior-safe filter", "Family peace-of-mind"), ""),
  mk("a-medical", "accessibility", "Medical condition", "notes=medical|dialysis|therapy",
    ["Doctor letter (private)", "Hospital proximity"],
    "Sharing PGs within 2km of {{hospital}}; on-call cab tie-up.",
    "same-day", w("Private handling", "Hospital-radius filter", "Care nearby"), ""),
  mk("a-lift-required", "accessibility", "Lift required (post-injury)", "notes=injury|surgery",
    ["Injury duration", "Ground floor alternative?"],
    "Sharing lift-only options or ground-floor rooms.",
    "same-day", w("Refund prevention", "Auto-filter no-lift out", "Recovery uninterrupted"), ""),
  mk("a-ground-floor", "accessibility", "Ground floor only", "ground-floor requested",
    ["Ground-floor rooms available"],
    "Sharing ground-floor rooms only.",
    "same-day", w("Filter enforced", "Zero mismatched tours", "Client trust"), ""),
  mk("a-women-safety", "accessibility", "Women-only + safety", "gender=f & safety mentioned",
    ["Warden availability", "CCTV coverage", "Curfew policy"],
    "Sharing women-only PGs — warden 24×7, CCTV all common areas.",
    "same-day", w("Filters women-only supply", "Family confidence", "Parents comfortable"), ""),
  mk("a-cctv", "accessibility", "CCTV mandatory", "safety flagged",
    ["CCTV coverage map", "Recording retention"],
    "Sharing CCTV-covered PGs with 30d retention.",
    "reply in 2h", w("Compliance-ready", "Trust marker", "Client safer"), ""),
  mk("a-security", "accessibility", "24×7 security", "safety flagged",
    ["Guard shift plan", "Visitor register"],
    "Sharing PGs with 24×7 guard + visitor register.",
    "reply in 2h", w("Insurance-lite", "Safety filter", "Peace-of-mind"), ""),
  mk("a-fire-safety", "accessibility", "Fire safety audit", "high-rise",
    ["Fire NOC copy", "Extinguisher photo"],
    "Sharing fire-NOC certified PGs.",
    "reply in 4h", w("Compliance", "Audit-ready", "Safer stay"), ""),
  mk("a-single-woman", "accessibility", "Single woman relocating alone", "gender=f & family absent",
    ["Local emergency contact", "Warden mobile"],
    "Sharing PGs with warden + local emergency circle.",
    "same-day", w("Retention up", "Safety-first filter", "Independence + safety"), ""),

  // ---------- DOCUMENTATION (8) ----------
  mk("d-aadhaar-missing", "documentation", "Aadhaar missing", "docs missing aadhaar",
    ["Any govt ID", "Aadhaar apply date"],
    "Can proceed with passport/PAN; Aadhaar within 30d of move-in.",
    "reply in 2h", w("Doesn't kill lead", "Interim doc policy", "No stall"), ""),
  mk("d-pan-missing", "documentation", "PAN missing", "docs missing pan",
    ["Form 60", "PAN apply proof"],
    "Form 60 works for rent — no PAN needed to check in.",
    "reply in 2h", w("Doc-friction removed", "Form-60 template", "Move-in unblocked"), ""),
  mk("d-passport-pending", "documentation", "Passport pending", "docs missing passport",
    ["Application receipt", "Expected date"],
    "OK to move in on Aadhaar; passport update within 45d.",
    "reply in 4h", w("Foreign-student catch", "Interim policy", "Not blocked"), ""),
  mk("d-visa", "documentation", "Visa validity check", "intl student",
    ["Visa scan", "Expiry vs stay end"],
    "Confirming visa covers stay period — sending owner NOC template.",
    "same-day", w("Compliance", "Visa-stay match check", "Legal stay"), ""),
  mk("d-police-verif", "documentation", "Police verification pending", "state requires PV",
    ["PV form status", "Local PS"],
    "PV form pre-filled; we submit on your behalf.",
    "reply in 4h", w("Compliance ownership", "Auto-fill PV form", "Zero paperwork"), ""),
  mk("d-foreign-national", "documentation", "Foreign national FRRO", "nationality!=IN",
    ["FRRO registration proof"],
    "Handling FRRO with local liaison; ₹0 to client.",
    "same-day", w("Compliance", "Liaison assigned", "Legal stay"), ""),
  mk("d-address-proof", "documentation", "Address proof mismatch", "current addr differs from ID",
    ["Utility bill", "Rental agreement current"],
    "Utility bill works; sending template if landlord signature needed.",
    "reply in 4h", w("Doc-friction removed", "Template ready", "Move-in unblocked"), ""),
  mk("d-college-id-only", "documentation", "College ID only (fresher)", "fresher & docs=college-id",
    ["College ID scan", "Admission letter"],
    "College ID + admission letter is sufficient.",
    "reply in 2h", w("Fresher-friendly", "Reduced doc checks", "Fast move-in"), ""),

  // ---------- RISK (9) ----------
  mk("r-fake-docs", "risk", "Fake document detected", "doc AI flag",
    ["OCR mismatch", "Manual verification note", "Escalation to manager"],
    "Hold move-in; requesting original doc verification in person.",
    "immediate", w("Fraud prevention", "Auto-flag + escalate", "Genuine clients protected"), ""),
  mk("r-fake-payment", "risk", "Fake payment screenshot", "screenshot without bank confirm",
    ["Bank ref check", "UTR verification"],
    "Awaiting UTR bank-side match before confirming.",
    "immediate", w("Chargeback prevention", "UTR check gate", "Genuine clients unaffected"), ""),
  mk("r-duplicate-booking", "risk", "Duplicate booking (same phone)", "phone matches booked lead",
    ["Prior booking id", "Refund status"],
    "This phone has an active booking. Confirming intent to switch.",
    "immediate", w("Double-charge prevention", "Duplicate alert", "No confusion"), ""),
  mk("r-chargeback", "risk", "Chargeback risk (past history)", "phone had past chargeback",
    ["Past dispute notes", "Payment mode restriction"],
    "Requesting UPI/cash for deposit (no card).",
    "same-day", w("Risk-tiered payment", "Auto-restrict cards", "Trust rebuilt slowly"), ""),
  mk("r-broker-scam", "risk", "Broker impersonation", "third-party asking commission",
    ["Third-party WA screenshot", "Direct-lead verification"],
    "Confirming direct lead — no broker fee applies.",
    "immediate", w("Brand protection", "Direct-check gate", "No hidden fee"), ""),
  mk("r-owner-fraud", "risk", "Owner listing fraud", "photos AI-flag or ownership dispute",
    ["Ownership doc", "Municipal record"],
    "Property flagged — moving lead to verified alt.",
    "immediate", w("Supply integrity", "Auto-swap listing", "Client safe"), ""),
  mk("r-identity-mismatch", "risk", "Identity mismatch at check-in", "ID vs face mismatch",
    ["Selfie + ID", "Manager approval"],
    "Hold move-in; manager verification in 30m.",
    "immediate", w("Fraud gate", "Escalate flow", "Genuine clients fast-tracked"), ""),
  mk("r-suspicious", "risk", "Suspicious behaviour (multiple leads)", "same person, 5+ leads / week",
    ["Behavior log", "Manager review"],
    "Manager review scheduled before next tour.",
    "same-day", w("Fraud discovery", "Behavior score", "Real clients unaffected"), ""),
  mk("r-underage", "risk", "Underage without guardian", "age<18 & no guardian",
    ["Guardian NOC", "Parent WA loop"],
    "Requesting guardian NOC before booking.",
    "same-day", w("Legal protection", "Guardian-NOC template", "Compliant stay"), ""),

  // ---------- OPERATIONS (10) ----------
  mk("o-late-movein", "operations", "Late move-in (>3d after commit)", "moveDate slipped",
    ["Reason", "New date"],
    "Confirming new date; hold room till {{newDate+1}}.",
    "same-day", w("Reduce hold cost", "Auto-hold extension", "No penalty"), ""),
  mk("o-early-moveout", "operations", "Early move-out request", "stay<30d",
    ["Reason", "Refund policy"],
    "Sharing pro-rated refund and notice period.",
    "same-day", w("Compliance", "Policy auto-quote", "Fair exit"), ""),
  mk("o-deposit-refund", "operations", "Deposit refund dispute", "post-checkout",
    ["Damage photos", "Deduction breakdown", "Timeline"],
    "Sharing itemized breakdown; refund by {{date}}.",
    "reply in 24h", w("Trust marker", "Auto-itemization", "Fast refund"), ""),
  mk("o-food-complaint", "operations", "Food complaint", "mess-quality flag",
    ["Photo of meal", "Repeat pattern"],
    "Escalated to owner; menu revamp in 48h.",
    "reply in 4h", w("Churn prevention", "Escalation SLA", "Better meals"), ""),
  mk("o-maintenance", "operations", "Maintenance request", "any repair",
    ["Photo of issue", "Urgency level"],
    "Assigned to {{tech}}; ETA {{eta}}.",
    "reply in 2h", w("SLA visible", "Auto-assign", "Fast fix"), ""),
  mk("o-shift-room", "operations", "Room shift request", "post move-in",
    ["Reason", "Availability check"],
    "Sharing 2 alt rooms in same PG; move charges waived.",
    "reply in 4h", w("Retention", "Auto-availability", "Free shift"), ""),
  mk("o-upgrade", "operations", "Upgrade room", "budget up post move-in",
    ["New room type", "Delta rent"],
    "Sharing upgrade options; pro-rated for this month.",
    "reply in 2h", w("Higher AOV", "Upgrade path clear", "Better room"), ""),
  mk("o-downgrade", "operations", "Downgrade room", "budget down post move-in",
    ["Reason", "Availability"],
    "Sharing downgrade options; refund of delta.",
    "reply in 2h", w("Prevent churn", "Downgrade path", "Stay affordable"), ""),
  mk("o-guest-stay", "operations", "Guest stay request", "guest overnight",
    ["Guest ID", "Dates", "Owner approval"],
    "Guest approved for {{n}} nights; visitor register updated.",
    "reply in 2h", w("Policy-safe", "Auto-approval flow", "Hosting allowed"), ""),
  mk("o-parking", "operations", "Parking request", "vehicle owned",
    ["Vehicle no", "2W/4W", "Availability"],
    "Parking slot #{{n}} assigned; ₹{{fee}}/mo.",
    "reply in 2h", w("Ancillary revenue", "Slot map", "Vehicle safe"), ""),

  // ---------- LOSS REASONS (8) with revival ----------
  mk("x-no-lift", "loss-reason", "Lost — no lift", "lostReason=lift",
    ["Buildings with lift within 500m"],
    "Sharing 2 lift-buildings that just came online.",
    "trigger", w("Turns loss into deal", "Auto-revive on new lift supply", "Right building found"),
    "Revive when a lift-building lists in same area."),
  mk("x-no-parking", "loss-reason", "Lost — no parking", "lostReason=parking",
    ["Parking-ready supply"],
    "Sharing parking-inclusive options.",
    "trigger", w("Revenue recovery", "Auto-revive on parking supply", "Vehicle solved"),
    "Revive when parking-ready room vacates."),
  mk("x-far-office", "loss-reason", "Lost — office too far", "lostReason=distance",
    ["Options within 3km of new office"],
    "Sharing options within 3km of {{office}}.",
    "trigger", w("Recovery playbook", "Distance-first re-match", "Commute fixed"),
    "Revive if office changes / nearby supply opens."),
  mk("x-food", "loss-reason", "Lost — food", "lostReason=food",
    ["Menu revamp proof", "New mess partner"],
    "New mess partner from {{date}} — sending week's menu.",
    "trigger", w("Recovery playbook", "Auto-revive on mess change", "Better food"),
    "Revive when mess partner changes."),
  mk("x-price", "loss-reason", "Lost — price", "lostReason=price",
    ["Price change proof", "Deposit reduction"],
    "Price dropped ₹{{delta}}; deposit halved.",
    "trigger", w("Recovery playbook", "Auto-revive on price drop", "Fits budget now"),
    "Revive on price drop in same building."),
  mk("x-deposit", "loss-reason", "Lost — deposit high", "lostReason=deposit",
    ["EMI now available", "Reduced deposit"],
    "Deposit split into 3 EMIs — starts on your salary date.",
    "trigger", w("Recovery playbook", "EMI-nudge auto-sent", "Deposit unblocked"),
    "Revive when EMI policy applies."),
  mk("x-timing", "loss-reason", "Lost — timing (not now)", "lostReason=timing",
    ["Predicted return date"],
    "Circling back in {{d}} days as planned.",
    "trigger", w("Predicted return", "Calendar auto-nudge", "Right timing"),
    "Revive on predicted return date."),
  mk("x-family", "loss-reason", "Lost — family didn't approve", "lostReason=family",
    ["Parent WA loop", "Family-tour scheduled"],
    "Scheduling parent video-tour + reference call.",
    "trigger", w("Recovery playbook", "Parent-loop revival", "Family confident"),
    "Revive with parent-tour + references."),
];

export function scenariosByCategory(cat: ScenarioCategory) {
  return SCENARIOS.filter((s) => s.category === cat);
}
export const SCENARIO_CATEGORIES: ScenarioCategory[] = [
  "group", "budget", "lifestyle", "accessibility", "documentation", "risk", "operations", "loss-reason",
];
