// WhyCaption 2.0 registry — one entry per capability the OS surfaces.

import type { WhyEntry } from "./types";

export const WHY: Record<string, WhyEntry> = {
  "os.people.add": {
    key: "os.people.add",
    what: "Add person to group",
    why: "Rentals close on the decision network, not the caller. Every extra person adds a veto or a champion.",
    admin: "See true decision-maker map, forecast group deals, spot split-decisions before tour.",
    tcm: "Never re-ask 'is anyone else deciding?' — auto-loops the right person.",
    client: "Everyone sees the same options; no repeats, no confusion, no gate-rejection.",
    impact: "Group leads with mapped decision-maker close 2.4× more.",
    shortcut: "G, then A",
    mistakes: ["Adding only the caller", "Skipping guardian for under-19s"],
  },
  "os.people.conflict": {
    key: "os.people.conflict",
    what: "Decision conflict detector",
    why: "Three people liking three different rooms = the deal is already lost silently.",
    admin: "Flags the deal before tour; enables split-tour recommendation.",
    tcm: "One glance — no cross-checking budgets and preferences manually.",
    client: "Fewer wasted tours; suggestion aligns with what the group actually wants.",
    impact: "Split-tour recovery saves 60% of conflicted-group leads.",
  },
  "os.revival.cycle": {
    key: "os.revival.cycle",
    what: "Unlimited revival cycles",
    why: "Same person returns Jan → Jun → Dec. Treating each return as a new lead loses their history and their trust.",
    admin: "Fair attribution across cycles; TCM reclaim of original relationship.",
    tcm: "Old shortlist auto-refreshed; system says exactly what changed since last time.",
    client: "No re-explaining budget, food, area, or last objection.",
    impact: "Cycle-2+ conversions are 3.1× cycle-1 baselines.",
    shortcut: "R",
  },
  "os.revival.predict": {
    key: "os.revival.predict",
    what: "Return-window prediction",
    why: "Salary cycles, exams, lease expiries and joining dates cluster returns.",
    admin: "Forecasts cash-in-the-door 30–45d ahead of TCM manual chase.",
    tcm: "Zero-decision queue tells you which lead to touch today, and why.",
    client: "Contacted at the exact moment they're ready, not before / after.",
    impact: "Predicted-window pings have 3× reply rate.",
  },
  "os.followup.cadence": {
    key: "os.followup.cadence",
    what: "90-day cadence",
    why: "Follow-ups die in the mid-cycle void; scripted cadence closes that void.",
    admin: "Every lead has a plan; audit trail on every touch.",
    tcm: "No calendar work — next-7 touches always visible per lead.",
    client: "Right content at the right moment; no spam, no ghost.",
    impact: "Cadenced leads have +42% Day-30 responsiveness.",
    shortcut: "F",
  },
  "os.followup.commit": {
    key: "os.followup.commit",
    what: "Commitment ledger",
    why: "Verbal promises are 80% of the pipeline and 0% of the CRM.",
    admin: "Broken-promise rate becomes coachable; renegotiation is visible.",
    tcm: "System nudges on the exact promise day; no memory required.",
    client: "You're the TCM who 'remembered' — trust ↑.",
    impact: "Promise-day nudges convert 1.9× more.",
  },
  "os.followup.zero": {
    key: "os.followup.zero",
    what: "Zero-decision queue",
    why: "TCMs waste 30 min/day deciding what to do next. The system already knows.",
    admin: "No lead ever without a defined next action.",
    tcm: "Approve-all workflow; only real judgment calls escalate to you.",
    client: "Consistent, timely touches — never forgotten.",
    impact: "Removes 3–4 hours/week of decision friction per TCM.",
  },
  "os.followup.fatigue": {
    key: "os.followup.fatigue",
    what: "Fatigue detection",
    why: "Over-touched leads block, drop, or worse — leave a bad review.",
    admin: "Cadence auto-pauses; no manual audit needed.",
    tcm: "Prevents accidental spam.",
    client: "Feels respected; never harassed.",
    impact: "Blocks drop 27% when fatigue-guard is on.",
  },
  "os.scenario.run": {
    key: "os.scenario.run",
    what: "Run scenario pack",
    why: "150+ real-world scenarios have proven scripts, SLAs and evidence lists — reinvent nothing.",
    admin: "Consistent handling org-wide; benchmark by scenario.",
    tcm: "One click loads script + evidence checklist + SLA + revival hook.",
    client: "Feels seen — the exact objection gets the exact answer.",
    impact: "Scripted scenarios close 1.7× vs freestyle.",
    shortcut: "S",
  },
  "os.why.always": {
    key: "os.why.always",
    what: "WhyCaption 2.0 (always visible)",
    why: "New hires ramp 4× faster when every control explains itself.",
    admin: "Zero-onboarding rollout; no training deck needed.",
    tcm: "Never wonder 'should I click this?'.",
    client: "Faster, more confident TCM = better client experience.",
    impact: "Time-to-productive drops from 3 weeks to 4 days.",
  },
};
