// Multiple real use cases — one demo lead for every branch of the decision tree.
import type { Lead, LeadEvent, PropertyOption, Stage } from "./types";

const iso = (minsAgo: number) => new Date(Date.now() - minsAgo * 60_000).toISOString();
const inMins = (m: number) => new Date(Date.now() + m * 60_000).toISOString();
const day = (offset: number) => new Date(Date.now() + offset * 86_400_000).toISOString().slice(0, 10);

let seq = 0;
const ev = (kind: string, label: string, minsAgo: number, actor = "Riya"): LeadEvent => ({
  id: `e${++seq}`, at: iso(minsAgo), actor, kind, label,
});

const prop = (
  id: string, name: string, roomType: string, rent: number, distanceKm: number, matchPct: number,
  extra: Partial<PropertyOption> = {},
): PropertyOption => ({
  id, name, roomType, room: extra.room ?? "203", rent,
  deposit: extra.deposit ?? rent, maintenance: extra.maintenance ?? 5000,
  bookingAmount: extra.bookingAmount ?? 5000, availableFrom: extra.availableFrom ?? day(0),
  distanceKm, matchPct, why: extra.why ?? ["Budget", "Location", "Immediate availability"],
  concern: extra.concern, ...extra,
});

const BEIGE = prop("p-beige", "Beige Luxe", "Double", 18000, 1.4, 92, { room: "203", deposit: 17000 });
const AMBER = prop("p-amber", "Amber House", "Double", 16500, 2.1, 84, { room: "104", concern: "Food rated 3.8" });
const CEDAR = prop("p-cedar", "Cedar Nest", "Private", 22000, 0.9, 88, { room: "301", deposit: 22000 });
const MAPLE = prop("p-maple", "Maple Stay", "Triple", 12000, 3.2, 79, { room: "011" });

interface Draft extends Partial<Lead> { name: string; phone: string; stage: Stage; useCase: string }

const drafts: Draft[] = [
  {
    name: "Unknown — screenshot 1042", phone: "", useCase: "Identity cannot be resolved",
    stage: "IDENTITY_RESOLUTION", waAccount: "WA-04", waPresence: "NO_CHAT",
    identityNote: "Screenshot shows only “Bellandur 17k double” — number cropped out",
    labels: { timing: "TODAY", likelihood: "MEDIUM", problem: "NONE" },
    lastScreenshotAt: iso(30), events: [ev("CAPTURED", "Screenshot captured, number not readable", 32, "System")],
  },
  {
    name: "Sneha Rao", phone: "+91 98450 11223", useCase: "Two records on one number",
    stage: "DUPLICATE_REVIEW", waAccount: "WA-02", waPresence: "MULTIPLE_CHATS",
    duplicateOf: ["L-0091", "L-0417"],
    labels: { timing: "TODAY", likelihood: "HIGH" },
    lastCustomerMsgAt: iso(40), lastScreenshotAt: iso(45),
    chat: [{ at: iso(40), from: "CUSTOMER", text: "Hi, following up on the HSR room" }],
    events: [ev("CAPTURED", "Second lead created from a new screenshot", 45, "System")],
  },
  {
    name: "Rahul Sharma", phone: "+91 99862 44119", useCase: "Fresh WhatsApp lead, nobody owns it",
    stage: "UNOWNED", waAccount: "WA-04", waPresence: "ACTIVE_CHAT",
    labels: { timing: "IMMEDIATE", likelihood: "HIGH" },
    requirement: { area: "Bellandur", budget: 17000, roomType: "DOUBLE", moveIn: day(4) },
    lastCustomerMsgAt: iso(14), lastScreenshotAt: iso(15),
    chat: [{ at: iso(14), from: "CUSTOMER", text: "I need a double sharing in Bellandur around 17k from 20th" }],
    events: [ev("CAPTURED", "AI read area, budget, occupancy and move-in from the screenshot", 15, "System")],
  },
  {
    name: "Imran Qureshi", phone: "+91 90080 77321", useCase: "Old chat — is the requirement still alive?",
    stage: "IDENTIFIED", waAccount: "WA-01", waPresence: "OLD_CHAT",
    labels: { timing: "THIS_WEEK", likelihood: "MEDIUM" },
    requirement: { area: "Marathahalli" },
    lastCustomerMsgAt: iso(60 * 24 * 26), lastScreenshotAt: iso(60 * 30),
    events: [ev("CAPTURED", "Old conversation surfaced again", 60 * 30, "System")],
  },
  {
    name: "Divya Menon", phone: "+91 97400 55290", useCase: "Chat lives on another Gharpayy number",
    stage: "IDENTIFIED", waAccount: "WA-07", waPresence: "OTHER_GHARPAYY_NUMBER",
    owner: "Karan", ownerSince: iso(60 * 20),
    labels: { timing: "TODAY", likelihood: "HIGH" },
    lastCustomerMsgAt: iso(120), lastScreenshotAt: iso(130),
    events: [ev("CAPTURED", "Same customer already active on WA-02 with Karan", 130, "System")],
  },
  {
    name: "Aditya Bose", phone: "+91 89041 20044", useCase: "Qualification half done, reconstruction unverified",
    stage: "QUALIFYING", waAccount: "WA-02", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(25), nextAction: "QUALIFY", nextActionAt: inMins(9),
    labels: { timing: "IMMEDIATE", likelihood: "HIGH" },
    requirement: { area: "HSR Layout", budget: 15000, roomType: "DOUBLE" },
    engagement: { objectionIdentified: false },
    openQuestion: "Deposit?",
    lastCustomerMsgAt: iso(12), lastTeamMsgAt: iso(20), lastScreenshotAt: iso(22),
    chat: [
      { at: iso(24), from: "CUSTOMER", text: "Need something in HSR under 15k" },
      { at: iso(20), from: "TEAM", text: "Sure, sharing two options" },
      { at: iso(12), from: "CUSTOMER", text: "Deposit?" },
    ],
    events: [ev("CLAIM", "Riya claimed the lead — committed to QUALIFY in 15 minutes", 25)],
  },
  {
    name: "Farhan Ali", phone: "+91 96322 71180", useCase: "Budget below inventory — nearby alternative",
    stage: "MATCHING", waAccount: "WA-03", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(200), nextAction: "SHARE PROPERTY", nextActionAt: inMins(-14),
    labels: { timing: "TODAY", likelihood: "MEDIUM", problem: "BUDGET" },
    requirement: { area: "Koramangala", budget: 11000, roomType: "TRIPLE", moveIn: day(6), intent: "READY_TO_VISIT", decisionMaker: "SELF" },
    feasibility: "FIT WITH NEARBY AREA", matches: [MAPLE, AMBER],
    lastCustomerMsgAt: iso(35), lastTeamMsgAt: iso(90), lastScreenshotAt: iso(100),
    events: [ev("FEASIBILITY", "Feasibility: FIT WITH NEARBY AREA", 120)],
  },
  {
    name: "Priya Nair", phone: "+91 98801 33110", useCase: "Property shared, customer silent",
    stage: "PROPERTY_SHARED", waAccount: "WA-04", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(400), nextAction: "CALL", nextActionAt: inMins(6),
    labels: { timing: "THIS_WEEK", likelihood: "MEDIUM", problem: "NO_RESPONSE" },
    requirement: { area: "Bellandur", budget: 18000, roomType: "DOUBLE", moveIn: day(12), intent: "COMPARING", decisionMaker: "SELF", duration: "1 YEAR" },
    engagement: { propertyShared: true, mediaShared: true, priceDiscussed: true },
    matches: [BEIGE, AMBER], selectedPropertyId: "p-beige",
    lastTeamMsgAt: iso(180), lastCustomerMsgAt: iso(260), lastScreenshotAt: iso(190),
    events: [ev("PROPERTY_SHARED", "Beige Luxe shared with photos and price", 180)],
  },
  {
    name: "Karthik Iyer", phone: "+91 99001 76540", useCase: "Customer says “I can come tonight”",
    stage: "TOUR_READY", waAccount: "WA-01", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(300), nextAction: "SCHEDULE VISIT", nextActionAt: inMins(11),
    labels: { timing: "IMMEDIATE", likelihood: "VERY_HIGH" },
    requirement: { area: "Bellandur", budget: 18000, maxBudget: 19000, roomType: "DOUBLE", moveIn: day(2), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR", whoIsStaying: "SELF", nonNegotiables: ["FOOD"], officeOrCollege: "Embassy Tech Village" },
    engagement: { propertyShared: true, mediaShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true },
    matches: [BEIGE, CEDAR], selectedPropertyId: "p-beige", reconstructionVerified: true,
    lastCustomerMsgAt: iso(6), lastTeamMsgAt: iso(20), lastScreenshotAt: iso(8),
    chat: [
      { at: iso(30), from: "TEAM", text: "Beige Luxe, 203 double, ₹18,000" },
      { at: iso(6), from: "CUSTOMER", text: "I can visit around 6 today" },
    ],
    events: [ev("CALL", "Call — CONNECTED · TOUR READY", 20)],
  },
  {
    name: "Meghana S", phone: "+91 90350 88122", useCase: "Tour booked, TCM handover not accepted",
    stage: "TOUR_SCHEDULED", waAccount: "WA-02", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(600), nextAction: "TCM must accept handover", nextActionAt: inMins(-22),
    labels: { timing: "IMMEDIATE", likelihood: "HIGH" },
    requirement: { area: "HSR Layout", budget: 16500, roomType: "DOUBLE", moveIn: day(3), intent: "READY_TO_VISIT", decisionMaker: "PARENT", duration: "6 MONTHS" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true },
    matches: [AMBER], selectedPropertyId: "p-amber", reconstructionVerified: true,
    tour: { propertyId: "p-amber", propertyName: "Amber House", room: "104", at: `${day(0)} 6:00 PM`, handledBy: "TCM", tourOwner: "Nikhil (TCM)", handoverAccepted: false, propertyInformed: true, propertyAcknowledged: false },
    lastTeamMsgAt: iso(40), lastCustomerMsgAt: iso(55), lastScreenshotAt: iso(60),
    events: [ev("TOUR_SCHEDULED", "Tour scheduled — Amber House today 6:00 PM, handled by Nikhil (TCM)", 45)],
  },
  {
    name: "Rohit Verma", phone: "+91 97399 44012", useCase: "Customer en route, running late",
    stage: "EN_ROUTE", waAccount: "WA-04", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(900), nextAction: "Mark arrived", nextActionAt: inMins(18),
    labels: { timing: "IMMEDIATE", likelihood: "VERY_HIGH" },
    requirement: { area: "Bellandur", budget: 18000, roomType: "DOUBLE", moveIn: day(1), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true },
    matches: [BEIGE], selectedPropertyId: "p-beige", reconstructionVerified: true,
    tour: { propertyId: "p-beige", propertyName: "Beige Luxe", room: "203", at: `${day(0)} 6:00 PM`, handledBy: "OPERATOR", tourOwner: "Riya", handoverAccepted: true, propertyInformed: true, propertyAcknowledged: true, customerConfirmed: "LATE", eta: "20 minutes" },
    lastCustomerMsgAt: iso(9), lastTeamMsgAt: iso(11), lastScreenshotAt: iso(12),
    events: [ev("PRE_TOUR", "Running late — ETA 20 minutes, property updated", 9)],
  },
  {
    name: "Ankita Gupta", phone: "+91 88848 90021", useCase: "Tour live, room issue raised",
    stage: "TOUR_LIVE", waAccount: "WA-03", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(1200), nextAction: "Resolve live issue", nextActionAt: inMins(3),
    labels: { timing: "IMMEDIATE", likelihood: "HIGH" }, blocker: "ROOM ISSUE",
    requirement: { area: "Bellandur", budget: 22000, roomType: "PRIVATE", moveIn: day(5), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true },
    matches: [CEDAR], selectedPropertyId: "p-cedar", reconstructionVerified: true,
    tour: { propertyId: "p-cedar", propertyName: "Cedar Nest", room: "301", at: `${day(0)} 5:00 PM`, handledBy: "OPERATOR", tourOwner: "Riya", handoverAccepted: true, propertyInformed: true, propertyAcknowledged: true, customerConfirmed: "YES", metRepresentative: true, startedAt: iso(26) },
    lastScreenshotAt: iso(30), lastCustomerMsgAt: iso(28), lastTeamMsgAt: iso(27),
    events: [ev("TOUR_LIVE", "Tour started", 26), ev("TOUR_ISSUE", "Live visit issue — ROOM ISSUE", 4)],
  },
  {
    name: "Naveen Kumar", phone: "+91 99019 22087", useCase: "Tour done, quotation still missing",
    stage: "POST_TOUR", waAccount: "WA-01", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(1500), nextAction: "SEND QUOTE", nextActionAt: inMins(-8),
    labels: { timing: "IMMEDIATE", likelihood: "VERY_HIGH", journey: "POST_TOUR", problem: "PRICE" },
    blocker: "PRICE", openObjection: "PRICE",
    requirement: { area: "Bellandur", budget: 17000, maxBudget: 18000, roomType: "DOUBLE", moveIn: day(2), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR", whoIsStaying: "SELF", nonNegotiables: ["FOOD"] },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true, tourCompleted: true, objectionIdentified: true },
    matches: [BEIGE], selectedPropertyId: "p-beige", reconstructionVerified: true,
    tour: { propertyId: "p-beige", propertyName: "Beige Luxe", room: "203", at: `${day(0)} 12:00 PM`, handledBy: "OPERATOR", tourOwner: "Riya", handoverAccepted: true, propertyInformed: true, propertyAcknowledged: true, customerConfirmed: "YES", metRepresentative: true, startedAt: iso(70), completedAt: iso(40), reaction: "LIKED_IT", preferredRoom: "203", blocker: "PRICE" },
    lastCustomerMsgAt: iso(35), lastTeamMsgAt: iso(50), lastScreenshotAt: iso(38),
    events: [ev("TOUR_COMPLETED", "Tour completed — LIKED IT, room 203, blocker PRICE", 40)],
  },
  {
    name: "Shalini Prasad", phone: "+91 98862 55103", useCase: "Quote sent, waiting on parent approval",
    stage: "NEGOTIATING", waAccount: "WA-02", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(2000), nextAction: "FOLLOW-UP", nextActionAt: inMins(45),
    labels: { timing: "TODAY", likelihood: "HIGH", journey: "NEGOTIATING", problem: "PARENT_APPROVAL" },
    blocker: "NEEDS APPROVAL", openObjection: "NEEDS APPROVAL",
    requirement: { area: "HSR Layout", budget: 16500, roomType: "DOUBLE", moveIn: day(8), intent: "READY_TO_BOOK", decisionMaker: "PARENT", duration: "1 YEAR" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true, tourCompleted: true, quotationSent: true, objectionIdentified: true },
    matches: [AMBER], selectedPropertyId: "p-amber", reconstructionVerified: true,
    tour: { propertyId: "p-amber", propertyName: "Amber House", room: "104", at: `${day(-1)} 7:00 PM`, handledBy: "OPERATOR", tourOwner: "Riya", handoverAccepted: true, customerConfirmed: "YES", completedAt: iso(600), reaction: "LOVED_IT", preferredRoom: "104", blocker: "PARENT APPROVAL" },
    quote: { id: "Q-88120", propertyId: "p-amber", room: "104", roomType: "Double", actualRent: 16500, offerRent: 15900, deposit: 16500, maintenance: 5000, lockIn: "6 months", notice: "1 month", bookingAmount: 5000, validUntil: "8 PM today", moveIn: day(8), sentAt: iso(90), outcome: "NEEDS APPROVAL" },
    lastCustomerMsgAt: iso(60), lastTeamMsgAt: iso(90), lastScreenshotAt: iso(65),
    events: [ev("QUOTE_SENT", "Quote sent — Amber House at ₹15,900", 90), ev("QUOTE_OUTCOME", "Quote outcome — NEEDS APPROVAL (father decides tonight)", 60)],
  },
  {
    name: "Vikram Reddy", phone: "+91 90190 66214", useCase: "Discount above authority — approval requested",
    stage: "QUOTE_SENT", waAccount: "WA-04", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(700), nextAction: "Approval required", nextActionAt: inMins(20),
    labels: { timing: "IMMEDIATE", likelihood: "HIGH", problem: "PRICE" },
    approvalRequested: true, expectedPrice: 15500,
    requirement: { area: "Bellandur", budget: 16000, roomType: "DOUBLE", moveIn: day(3), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "6 MONTHS" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourCompleted: true, tourScheduled: true, tourDiscussed: true, quotationSent: true },
    matches: [BEIGE], selectedPropertyId: "p-beige", reconstructionVerified: true,
    quote: { id: "Q-88131", propertyId: "p-beige", room: "203", roomType: "Double", actualRent: 18000, offerRent: 17000, deposit: 17000, maintenance: 5000, lockIn: "6 months", notice: "1 month", bookingAmount: 5000, validUntil: "9 PM today", moveIn: day(3), sentAt: iso(40), outcome: "PRICE OBJECTION" },
    lastCustomerMsgAt: iso(15), lastTeamMsgAt: iso(40), lastScreenshotAt: iso(20),
    events: [ev("NEGOTIATE", "₹1,500 discount exceeds authority — approval requested, no verbal promise made", 15)],
  },
  {
    name: "Tanya Sethi", phone: "+91 99720 30045", useCase: "Booking created, property approval overdue",
    stage: "APPROVAL_PENDING", waAccount: "WA-03", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(1000), nextAction: "Property approval", nextActionAt: inMins(-31),
    labels: { timing: "IMMEDIATE", likelihood: "VERY_HIGH", journey: "TOKEN_PENDING" },
    requirement: { area: "Bellandur", budget: 18000, roomType: "DOUBLE", moveIn: day(4), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true, tourCompleted: true, quotationSent: true },
    matches: [BEIGE], selectedPropertyId: "p-beige", reconstructionVerified: true,
    quote: { id: "Q-88140", propertyId: "p-beige", room: "203", roomType: "Double", actualRent: 18000, offerRent: 17000, deposit: 17000, maintenance: 5000, lockIn: "6 months", notice: "1 month", bookingAmount: 5000, validUntil: "tonight", moveIn: day(4), sentAt: iso(200), outcome: "ACCEPTED" },
    booking: { id: "GP-01882", propertyId: "p-beige", propertyName: "Beige Luxe", room: "203", roomType: "Double", rent: 17000, deposit: 17000, maintenance: 5000, bookingAmount: 5000, discount: 1000, moveIn: day(4), lockIn: "6 months", notice: "1 month", quoteId: "Q-88140", leadOwner: "Riya", tourOwner: "Riya", createdBy: "Riya", createdAt: iso(120), inventoryApproval: "PENDING", commercialApproval: "PENDING" },
    lastTeamMsgAt: iso(110), lastCustomerMsgAt: iso(150), lastScreenshotAt: iso(115),
    events: [ev("BOOKING_CREATED", "Booking created — commercial terms frozen", 120), ev("APPROVAL", "Approval request sent to the property manager", 110)],
  },
  {
    name: "Suresh Babu", phone: "+91 90083 14477", useCase: "Room held, token partially paid",
    stage: "PAYMENT_PENDING", waAccount: "WA-01", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(1300), nextAction: "Collect balance", nextActionAt: inMins(12),
    labels: { timing: "IMMEDIATE", likelihood: "VERY_HIGH", journey: "TOKEN_PENDING" },
    blocker: "Balance ₹2,000 pending",
    requirement: { area: "Koramangala", budget: 12000, roomType: "TRIPLE", moveIn: day(2), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "6 MONTHS" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true, tourCompleted: true, quotationSent: true },
    matches: [MAPLE], selectedPropertyId: "p-maple", reconstructionVerified: true,
    quote: { id: "Q-88151", propertyId: "p-maple", room: "011", roomType: "Triple", actualRent: 12000, offerRent: 12000, deposit: 12000, maintenance: 5000, lockIn: "6 months", notice: "1 month", bookingAmount: 5000, validUntil: "tonight", moveIn: day(2), sentAt: iso(300), outcome: "ACCEPTED" },
    booking: { id: "GP-01888", propertyId: "p-maple", propertyName: "Maple Stay", room: "011", roomType: "Triple", rent: 12000, deposit: 12000, maintenance: 5000, bookingAmount: 5000, discount: 0, moveIn: day(2), lockIn: "6 months", notice: "1 month", quoteId: "Q-88151", leadOwner: "Riya", createdBy: "Riya", createdAt: iso(250), inventoryApproval: "YES", commercialApproval: "YES", roomHeldUntil: inMins(60) },
    payments: [{ id: "P-1", amount: 3000, paidTo: "GHARPAYY", mode: "UPI", proof: true, verified: true, at: iso(30) }],
    lastCustomerMsgAt: iso(25), lastTeamMsgAt: iso(28), lastScreenshotAt: iso(26),
    events: [ev("ROOM_HELD", "Room 011 held", 240), ev("PAYMENT", "₹3,000 UPI to GHARPAYY — proof YES, verified YES", 30)],
  },
  {
    name: "Nisha Jain", phone: "+91 97418 22366", useCase: "Payment proof uploaded but not verified",
    stage: "PAYMENT_PENDING", waAccount: "WA-02", waPresence: "ACTIVE_CHAT",
    owner: "Karan", ownerSince: iso(900), nextAction: "Verify payment", nextActionAt: inMins(-5),
    labels: { timing: "IMMEDIATE", likelihood: "VERY_HIGH" }, blocker: "PAYMENT VERIFICATION PENDING",
    requirement: { area: "HSR Layout", budget: 16500, roomType: "DOUBLE", moveIn: day(3), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true, tourCompleted: true, quotationSent: true },
    matches: [AMBER], selectedPropertyId: "p-amber", reconstructionVerified: true,
    quote: { id: "Q-88160", propertyId: "p-amber", room: "104", roomType: "Double", actualRent: 16500, offerRent: 16000, deposit: 16500, maintenance: 5000, lockIn: "6 months", notice: "1 month", bookingAmount: 5000, validUntil: "tonight", moveIn: day(3), sentAt: iso(400), outcome: "ACCEPTED" },
    booking: { id: "GP-01891", propertyId: "p-amber", propertyName: "Amber House", room: "104", roomType: "Double", rent: 16000, deposit: 16500, maintenance: 5000, bookingAmount: 5000, discount: 500, moveIn: day(3), lockIn: "6 months", notice: "1 month", leadOwner: "Karan", createdBy: "Karan", createdAt: iso(350), inventoryApproval: "YES", commercialApproval: "YES", roomHeldUntil: inMins(40) },
    payments: [{ id: "P-2", amount: 5000, paidTo: "PROPERTY", mode: "UPI", proof: true, verified: false, at: iso(20) }],
    lastCustomerMsgAt: iso(18), lastTeamMsgAt: iso(30), lastScreenshotAt: iso(22),
    events: [ev("PAYMENT", "₹5,000 UPI to PROPERTY — proof YES, verified NO", 20, "Karan")],
  },
  {
    name: "Deepak Rana", phone: "+91 96865 71100", useCase: "Property says the room is gone",
    stage: "APPROVAL_PENDING", waAccount: "WA-04", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(800), nextAction: "Offer alternative", nextActionAt: inMins(4),
    labels: { timing: "IMMEDIATE", likelihood: "HIGH", problem: "INVENTORY" },
    blocker: "Room unavailable: ALREADY BOOKED",
    requirement: { area: "Bellandur", budget: 22000, roomType: "PRIVATE", moveIn: day(5), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true, tourCompleted: true, quotationSent: true },
    matches: [CEDAR, BEIGE], selectedPropertyId: "p-cedar", reconstructionVerified: true,
    quote: { id: "Q-88170", propertyId: "p-cedar", room: "301", roomType: "Private", actualRent: 22000, offerRent: 21500, deposit: 22000, maintenance: 5000, lockIn: "6 months", notice: "1 month", bookingAmount: 5000, validUntil: "tonight", moveIn: day(5), sentAt: iso(300), outcome: "ACCEPTED" },
    booking: { id: "GP-01894", propertyId: "p-cedar", propertyName: "Cedar Nest", room: "301", roomType: "Private", rent: 21500, deposit: 22000, maintenance: 5000, bookingAmount: 5000, discount: 500, moveIn: day(5), lockIn: "6 months", notice: "1 month", leadOwner: "Riya", createdBy: "Riya", createdAt: iso(200), inventoryApproval: "NO", commercialApproval: "PENDING", approvalNote: "ALREADY BOOKED" },
    lastTeamMsgAt: iso(30), lastCustomerMsgAt: iso(60), lastScreenshotAt: iso(35),
    events: [ev("APPROVAL", "Room unavailable — ALREADY BOOKED; alternative flow opened", 20)],
  },
  {
    name: "Aisha Khan", phone: "+91 99457 88991", useCase: "Reserved — check-in readiness tomorrow",
    stage: "CHECKIN_READY", waAccount: "WA-03", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(4000), nextAction: "Check-in day contact", nextActionAt: inMins(300),
    labels: { timing: "TODAY", likelihood: "VERY_HIGH", journey: "BOOKED" },
    requirement: { area: "Bellandur", budget: 18000, roomType: "DOUBLE", moveIn: day(1), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true, tourCompleted: true, quotationSent: true },
    matches: [BEIGE], selectedPropertyId: "p-beige", reconstructionVerified: true,
    booking: { id: "GP-01870", propertyId: "p-beige", propertyName: "Beige Luxe", room: "203", roomType: "Double", rent: 17000, deposit: 17000, maintenance: 5000, bookingAmount: 5000, discount: 1000, moveIn: day(1), lockIn: "6 months", notice: "1 month", leadOwner: "Riya", createdBy: "Riya", createdAt: iso(3000), inventoryApproval: "YES", commercialApproval: "YES", roomHeldUntil: inMins(600), finalRoomLock: true, customerConfirmed: true },
    payments: [{ id: "P-3", amount: 5000, paidTo: "GHARPAYY", mode: "UPI", proof: true, verified: true, at: iso(2900) }],
    checkin: { roomReady: false, cleaning: true, bed: true, cupboard: true, wifi: false, keys: false, balanceKnown: true, balanceAmount: 12000 },
    lastTeamMsgAt: iso(120), lastCustomerMsgAt: iso(200), lastScreenshotAt: iso(130),
    events: [ev("RESERVED", "RESERVED — approval, hold, verified payment and customer confirmation all in place", 2800), ev("CHECKIN", "Check-in readiness failed — escalated", 100)],
  },
  {
    name: "Mohit Saini", phone: "+91 98868 12093", useCase: "Checked in, settlement open",
    stage: "CHECKED_IN", waAccount: "WA-01", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(9000),
    labels: { timing: "TODAY", likelihood: "VERY_HIGH", journey: "BOOKED" },
    requirement: { area: "Koramangala", budget: 12000, roomType: "TRIPLE", moveIn: day(-1), intent: "READY_TO_BOOK", decisionMaker: "SELF", duration: "1 YEAR" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true, tourDiscussed: true, tourScheduled: true, tourCompleted: true, quotationSent: true },
    matches: [MAPLE], selectedPropertyId: "p-maple", reconstructionVerified: true,
    booking: { id: "GP-01840", propertyId: "p-maple", propertyName: "Maple Stay", room: "011", roomType: "Triple", rent: 12000, deposit: 12000, maintenance: 5000, bookingAmount: 5000, discount: 0, moveIn: day(-1), lockIn: "6 months", notice: "1 month", leadOwner: "Riya", createdBy: "Riya", createdAt: iso(8000), inventoryApproval: "YES", commercialApproval: "YES", finalRoomLock: true, customerConfirmed: true },
    payments: [{ id: "P-4", amount: 17000, paidTo: "SPLIT", mode: "BANK", proof: true, verified: true, at: iso(1500) }],
    checkin: { roomReady: true, cleaning: true, bed: true, cupboard: true, wifi: true, keys: true, balanceKnown: true, balanceAmount: 0, handedOver: true, inspected: true, balanceCollected: true },
    lastScreenshotAt: iso(600),
    events: [ev("CHECKED_IN", "CHECKED IN — lead pipeline ends, booking moves to active stay", 500)],
  },
  {
    name: "Pooja Bhat", phone: "+91 90350 41122", useCase: "Future lead with dated follow-up",
    stage: "FUTURE", waAccount: "WA-02", waPresence: "ACTIVE_CHAT",
    owner: "Riya", ownerSince: iso(6000), nextAction: "FOLLOW-UP", nextActionAt: inMins(60 * 24 * 12),
    followUpAt: day(12), futureDecisionAt: day(20),
    labels: { timing: "FUTURE", likelihood: "MEDIUM", problem: "DECISION_DELAY" },
    requirement: { area: "Whitefield", budget: 14000, roomType: "DOUBLE", moveIn: day(45), intent: "COMPARING", decisionMaker: "SELF", duration: "1 YEAR" },
    lastScreenshotAt: iso(600), lastCustomerMsgAt: iso(700), lastTeamMsgAt: iso(690),
    events: [ev("FUTURE", `Future lead — move-in ${day(45)}, decision ${day(20)}, follow-up ${day(12)}`, 600)],
  },
  {
    name: "Gaurav Malhotra", phone: "+91 99456 70012", useCase: "Lost to a competitor",
    stage: "LOST", waAccount: "WA-04", waPresence: "ACTIVE_CHAT",
    owner: "Karan", ownerSince: iso(7000), lostReason: "BOOKED ELSEWHERE — Zolo Whitefield",
    labels: { timing: "THIS_WEEK", likelihood: "LOW", problem: "PRICE" },
    requirement: { area: "Whitefield", budget: 13000, roomType: "DOUBLE", moveIn: day(-2), intent: "COMPARING", decisionMaker: "SELF", duration: "6 MONTHS" },
    engagement: { propertyShared: true, priceDiscussed: true, callDone: true },
    lastScreenshotAt: iso(2000),
    events: [ev("LOST", "Lost — BOOKED ELSEWHERE (Zolo Whitefield)", 1800, "Karan")],
  },
];

export function seedLeads(): Lead[] {
  return drafts.map((d, i) => ({
    id: `MM-${String(i + 1).padStart(3, "0")}`,
    name: d.name, phone: d.phone, waAccount: d.waAccount ?? "WA-01",
    waPresence: d.waPresence ?? "ACTIVE_CHAT", duplicateOf: d.duplicateOf, identityNote: d.identityNote,
    owner: d.owner, ownerSince: d.ownerSince, handoverTo: d.handoverTo,
    stage: d.stage, nextAction: d.nextAction, nextActionAt: d.nextActionAt,
    channel: d.channel ?? "WHATSAPP", blocker: d.blocker, lostReason: d.lostReason,
    futureDecisionAt: d.futureDecisionAt, followUpAt: d.followUpAt,
    labels: d.labels ?? {}, requirement: d.requirement ?? {}, reconstructionVerified: d.reconstructionVerified,
    engagement: d.engagement ?? {}, feasibility: d.feasibility, matches: d.matches ?? [],
    selectedPropertyId: d.selectedPropertyId, rejectionReason: d.rejectionReason,
    tour: d.tour, quote: d.quote, booking: d.booking, payments: d.payments ?? [],
    checkin: d.checkin, settlement: d.settlement,
    openQuestion: d.openQuestion, openObjection: d.openObjection,
    expectedPrice: d.expectedPrice, approvalRequested: d.approvalRequested,
    lastCustomerMsgAt: d.lastCustomerMsgAt, lastTeamMsgAt: d.lastTeamMsgAt, lastScreenshotAt: d.lastScreenshotAt,
    chat: d.chat ?? [], events: d.events ?? [], useCase: d.useCase,
  }));
}
